### ISSUE TITLE
Handlers issue

### ISSUE THREAD

**Issue by KsavinN** [jupyterlab/debugger#102]
![chrome-capture (10)](https://user-images.githubusercontent.com/34033913/67663323-83d07280-f965-11e9-8fd4-862839d98a5b.gif)

Now the issue look like that :
![breakpoints_issue](https://user-images.githubusercontent.com/34033913/68472690-50bd9700-0221-11ea-9244-cb71deb2aa12.gif)

**Comment by jtpio** [comment]
Might be related to https://github.com/jupyterlab/debugger/issues/101.

**Comment by KsavinN** [comment]
![chrome-capture (11)](https://user-images.githubusercontent.com/34033913/67757561-599db400-fa3c-11e9-88e6-6ea1ff06d008.gif)

Same issue with console. It appears after reloading page

**Comment by KsavinN** [comment]
Resolved in #163
