### ISSUE TITLE
Wrong breakpoints display during change console

### ISSUE THREAD

**Issue by KsavinN** [jupyterlab/debugger#115]
![chrome-capture (14)](https://user-images.githubusercontent.com/34033913/67760209-2f022a00-fa41-11e9-975d-9369a601148f.gif)

**Comment by KsavinN** [comment]
It can be resolved after merge #114

**Comment by jtpio** [comment]
Yes it looks like the consoles have suffered a bit from the past changes.

Another example when executing code in an `xpython` console:

![console-cell-breakpoint](https://user-images.githubusercontent.com/591645/68120537-ed242880-ff05-11e9-8358-4cf1a2f80dae.gif)

**Comment by KsavinN** [comment]
This issue is seems resolved after implement restored signal in BreakpoinModel.
