### ISSUE TITLE
Breakpoints on the gutter

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/debugger#119]
Currently, clicking the gutter directly adds the breakpoint [marker](https://github.com/jupyterlab/debugger/blob/master/src/handlers/cell.ts#L177).

The correct behavior would be to add this marker when the model signals a change in its breakpoints.

**Comment by jtpio** [comment]
This will also be useful for https://github.com/jupyterlab/debugger/issues/103.

**Comment by jtpio** [comment]
Better to tackle this one before https://github.com/jupyterlab/debugger/issues/103
