### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#12]
Since #9 is going to add some tests, we can start thinking about what we want to use to run them automatically.

The 2 main options at the moment seem to be:
- Azure pipelines: already used for the main JupyterLab repo
- [GitHub actions](https://github.com/features/actions): now available in beta, looking promising (and also arguably easier to configure?)

**Comment by jtpio** [comment]
I would be willing to try the GitHub actions, especially since the tests are for now very simple.

**Comment by afshin** [comment]
I think exploring the GitHub options is a great idea.

If you do decide it's worthwhile and the one we should use, maybe you can do a short walk through on [Wednesday's JupyterLab meeting](https://calpoly.zoom.us/j/2261836383) at 9AM PT.

**Comment by jtpio** [comment]
Yes, and I think it was also brought up on the JupyterLab gitter channel.

**Comment by jtpio** [comment]
OK just signed up for the GitHub actions beta (access requested, not enabled yet)

**Comment by jtpio** [comment]
To have the GiHub Actions enabled on this repo, it looks like we will maybe need to sign up for the beta for the `jupyterlab` organization: https://github.com/features/actions.

(in other words having it enabled for a single user *might* not be enough)
