### ISSUE TITLE
Audit style conventions in TS classes

### ISSUE THREAD

**Issue by afshin** [jupyterlab/debugger#139]
We should follow the JupyterLab TS `class` conventions. These rules are how most JupyterLab and PhosphorJS classes are constructed.

Classes should be composed in this order:

1. `constructor` always appears first.
1. Public attributes (both `readonly` and those with getters/setters) appear next.
1. Public methods come next. The `public` keyword is unnecessary. All `public` methods should begin with a lowercase letter.
1. `protected` methods should appear next. All `protected` methods should begin with a lowercase letter.
1. `private` methods should follow. All `private` methods should begin with an `_` (underscore) so that as a user reads the code, they know they are looking at a `private` method/variable that cannot be inherited or used publicly.
1. `private` variables should appear last, at the bottom of a `class` definition.

If a `class` has static methods, the `static` keyword should not be used; *instead* the static methods should be defined in a separate `namespace` that has the same name as the class. In this way, `static` methods will not be conflated with `instance` methods.

cc: @KsavinN @jtpio @JohanMabille 

cf. [JupyterLab TypeScript Style Guide](https://github.com/jupyterlab/jupyterlab/wiki/TypeScript-Style-Guide)

**Comment by afshin** [comment]
Here is an example of the pattern described above:

```typescript
export class Foo {
  constructor(options: Foo.IOptions = {}) {
    console.log('options', options);
  }

  readonly bar = true;

  get baz(): string {
    return this._baz;
  }
  set baz(baz: string) {
    this._baz = baz || 'empty';
  }

  qux(): void {
    console.log('Foo#qux() was called');
  }

  async quux(): Promise<void> {
    return;
  }

  protected quuz(): boolean {
    return Math.random() > 0.5;
  }

  protected async corge(): Promise<void> {
    this._grault();
    return this._garply();
  }

  private _grault(): void {
    console.log('Foo#_grault() was called');
  }

  private async _garply(): Promise<void> {
    return;
  }

  private _baz = '';
}

export namespace Foo {
  export interface IOptions {}

  export function create(): Foo {
    return new Foo();
  }
}
```

**Comment by afshin** [comment]
Keep in mind that *all* methods (`public`, `protected` and `private`) should have doc strings.

All `public` and `protected` attributes should have doc strings as well.

**Comment by jtpio** [comment]
Thanks @afshin for writing this down.

We should definitely follow this style every time we make a change. Maybe there are also some TSLint / ESLint rules that can help automated the process?

**Comment by afshin** [comment]
It turns out I didn't need to write this down because there already exists a resource with these rules, the [JupyterLab TypeScript Style Guide](https://github.com/jupyterlab/jupyterlab/wiki/TypeScript-Style-Guide) on the repo's Wiki.

I didn't think that the API order of a class was something you could modify with those tools.

I think import order *is*, though, so that's a good idea. I don't think we are using it in core. Perhaps we should add it to the core JupyterLab repo and also here.

**Comment by jtpio** [comment]
Something that can also be streamlined is the use of arrow functions within a class.

At the moment the `DebugService` in [`service.ts`](https://github.com/jupyterlab/debugger/blob/ffdd985e69247d9bc39249d98ff57c44b6d84cb8/src/service.ts) uses a mix of both, but we should stick to one (non-arrow function for class methods).

**Comment by jtpio** [comment]
Another thing that can be normalized across the code base is the use of getters for class methods that return a `boolean` and are usually named `isEnabled` or `isStarted`.

At the moment there is a mix of the two styles.

**Comment by jtpio** [comment]
This should now be fixed (see linked PRs above for more details).

We should also now make sure that we follow the style conventions for every new PR.

@afshin feel free to re-open the issue if you think something is missing or should be changed.
