### ISSUE TITLE
Variable display enhancement

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#141]
At the moment variables are displayed like this:

![image](https://user-images.githubusercontent.com/591645/68114993-a9c2bd80-fef7-11e9-825e-038289477a7a.png)

Ideally we would display the value of an `int` directly, using the `type` information for the syntax highlighting (parsing the value with `parseInt` or `parseFloat` for instance). Similar thing for strings.

`evaluateName` and other fields coming from the debug adapter protocol can also be removed.

**Comment by KsavinN** [comment]
Yesterday I tried to get your suggestion of displaying results. But the cause, for now, react inspector 
don't have logic to set for some proper to not render (even within nodeRender).

**Comment by jtpio** [comment]
Some of this was fixed in #125, and the rest can be tracked in #177.
