### ISSUE TITLE
Create a function for adding toolbar buttons.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/debugger#154]
Create a helper function that adds the default debugger launch command to the toolbar of a `ConsolePanel` or `NotebookPanel` *only if its kernel supports debugging*. This function should be called from within the `consoles` plugin and the `notebooks` plugin.

```typescript
/**
 * Adds a toolbar button to open the debugger.
 */
function updateToolbar(widget: MainAreaWidget<ConsolePanel | NotebookPanel>): void {
  /* ... */
}
```

**Comment by jtpio** [comment]
This was addressed in #239.
