### ISSUE TITLE
Default mode

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#174]
The debugger is open in expanded mode by default when started in a fresh new workspace (after a reset for example):

![debugger-default-mode](https://user-images.githubusercontent.com/591645/68707711-95835e00-0592-11ea-8e6d-21338e01cdd0.gif)

Should that be the default behavior? Or should it start as a sidebar (condensed) instead?

**Comment by SylvainCorlay** [comment]
Since the  extra content for the main-area widget is partly a placeholder for now, I think that it makes sense to make the sidebar version the default.
