### ISSUE TITLE
Display nested data structures

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#177]
Now that #125 has been merged, we can request more variables when expanding a tree node.

However we don't support nested data structures yet, such as a `dict` in a `dict`:

![image](https://user-images.githubusercontent.com/591645/68774630-afbe4a00-062d-11ea-899e-3e75622cef78.png)

But it looks like we could do some further refactoring, and end up having:

- The current scopes and variables, as returned by the DAP, stored in memory in the model
- A mapper that transforms the data from the DAP, and maintains a JSON-like data structure that represents the variables as the state
- The react view that consumes the JSON-like state and renders the tree as is
- The tree view component should also support events when a node is expanded
- On expand, a request is sent to the kernel to retrieve more information for the variable using the `variableReference`

There is already some of this logic in the current implementation, but we should try to separate the state management, rendering and event handling even more.

Also we should check whether or not the current `variableExpanded` signal is needed in the model. Or if we can make the request for more variables via the service directly:

https://github.com/jupyterlab/debugger/blob/8192e8a4185d2f4d8f77b937cd10ba752d7b0531/src/variables/index.ts#L82-L84

**Comment by jtpio** [comment]
At the moment, there is a short period of time where we see the previous content:

![image](https://user-images.githubusercontent.com/591645/68784856-89a0a600-063d-11ea-85cf-670bbf0f688b.png)

As a workaround we could check if it's possible to override the empty dict when the node is collapsed.

This was introduced in https://github.com/jupyterlab/debugger/pull/125/commits/dbead195a59b24f12c80fc43db2960939ee650f3

**Comment by KsavinN** [comment]
#347
