### ISSUE TITLE
[VariableInspector] Hide private attributes/methods by default

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/debugger#179]
Displaying all private `_*` and dunder `__*__` attributes/methods adds a lot of clutter. It would be good to collect these under top level `_` and `__` keys so users can  more easily focus on what is important/relevant.

A case in point is ipython where the tab completion doesn't show any attributes/methods starting with an underscore unless the user explicitly types `_` before requesting completions.

**Comment by jtpio** [comment]
Thanks @dhirschfeld, this is a good idea.

There could be a pattern that filters some of these variables. For now even `ptvsd` shows up in the list because of the way the debugger is started.

**Comment by martinRenou** [comment]
As discussed in #314, I wonder if it would not be a good idea to hide any ptvsd related variables?

**Comment by jtpio** [comment]
For now they show up as a side-effect of using `ptvsd` in interactive mode:

```python
import ptvsd
ptvsd.enable_attach(...)
```

**Comment by jtpio** [comment]
Moving to 0.2.0.

We should indeed filter these attributes, even if for now it results in having a list in the settings.
