### ISSUE TITLE
Close the debugger panel

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/debugger#181]
When the last notebook is closed, the debugger panel should be closed.

**Comment by jtpio** [comment]
What if there are still consoles open? (and in the future also files)

**Comment by JohanMabille** [comment]
Alright, more precisely the debugger panel should be closed when the last kernel that supports debugging has no more clients (notebook and / or consoles).

**Comment by jtpio** [comment]
:+1: 

It's somehow related to the what kind of UI element we want to show the users, so they know debugging is possible or not.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/debugger/pull/505
