### ISSUE TITLE
Expanding variables and switching frames

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#183]
Something noticed while implementing #182: if a node is expanded in the variable inspector and we switch frames, the same node will also be expanded in the other frame.

![variable-expand-node-state](https://user-images.githubusercontent.com/591645/68853763-00d84780-06db-11ea-9932-c53ba61c04b8.gif)

It seems to be related to the state of the variables component.

**Comment by KsavinN** [comment]
#347
