### ISSUE TITLE
In Multiple notebook display need double click for set gutter in other notebook

### ISSUE THREAD

**Issue by KsavinN** [jupyterlab/debugger#191]
![firstclickdontWork](https://user-images.githubusercontent.com/34033913/68897883-aff23e80-072e-11ea-8f92-ed3519c4d6d2.gif)

**Comment by jtpio** [comment]
What should the behavior be?

The hover marker probably needs to take into account whether the notebook widget has the focus or not (so it doesn't show the markers on hover).

**Comment by KsavinN** [comment]
It still creates breakpoint after one click. Should adding breakpoint only work for one widget?

**Comment by KsavinN** [comment]
was resolved #190
