### ISSUE TITLE
Gutter Click for split console set in both gutter

### ISSUE THREAD

**Issue by KsavinN** [jupyterlab/debugger#194]
![consoleSwittchinGutterPROBLEM](https://user-images.githubusercontent.com/34033913/68950246-0b1e4280-07bc-11ea-82c3-86e5590cbe6c.gif)

**Comment by jtpio** [comment]
If the consoles use the same kernel, then it is somehow expected behavior.

The content of the prompt is empty on both sides, so it will map to the same hash and the breakpoints will correspond to the same "editor".

**Comment by jtpio** [comment]
For consoles not sharing the same kernel, the breakpoints "stick" to the correct console:

![console-gutters-different-kernels](https://user-images.githubusercontent.com/591645/70521257-2ff9a180-1b3f-11ea-9470-c0dfca48658f.gif)

For consoles sharing the same kernel:

![console-gutters-same-kernels](https://user-images.githubusercontent.com/591645/70521253-2d974780-1b3f-11ea-9c25-50a3ee2a0716.gif)

I think it's fine to close this issue for now, and open new ones if this ends up being too confusing for the users.
