### ISSUE TITLE
Extra dumpCell request sent

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/debugger#202]
After a breakpoint is hit and the execution is resumed with `Next` until it reaches the end, an extra `dumpCell` request is sent to the backend. From the callstack, the root cause seems to be the activity monitor:

```typescript
handlers/cells.ts: 156
      this._cellMonitor.activityStopped.connect(() => {
        this.sendEditorBreakpoints();
      }, this);
```

**Comment by jtpio** [comment]
To reproduce:

![extra-dumpcell](https://user-images.githubusercontent.com/591645/69137104-5e460d00-0abc-11ea-8395-eb5962290285.gif)

The activity monitor uses the `this.activeCell.model.contentChanged` signal. It is possible that this signal is also emitted when the cell is executed.

**Comment by jtpio** [comment]
We could try using `this.activeCell.model.value.changed` instead.
