### ISSUE TITLE
Should the debugger lifecycle be managed by a toggleable button?

### ISSUE THREAD

**Issue by afshin** [jupyterlab/debugger#214]
- We should only make a debugger button/toggle available in the toolbar of consoles and notebooks that have kernels that handle debugging.
- If we make the "button" actually be a toggle/switch/checkbox which indicates whether the kernel in question has currently started or stopped debugging, then it could allow users to switch between notebooks and have the debugger UI *only* show the last *active/started* debuggable kernel's state.
  - This means that if you open up notebook **foo.ipynb** and start its debugger, the debugger UI appears and tracks notebook **foo.ipynb**'s kernel state.
  - If you then open up notebook **bar.ipynb** and *do not* toggle its debugger, then you can still see the state of notebook **foo.ipynb** even if the active notebook that has the focus is notebook **bar.ipynb**.

cf. https://github.com/jupyterlab/debugger/issues/180

**Comment by jtpio** [comment]
Fixed by #239.
