### ISSUE TITLE
Issue after close widget which have stopped thread (during debugging state)

### ISSUE THREAD

**Issue by KsavinN** [jupyterlab/debugger#215]
![closeDuringDebugg](https://user-images.githubusercontent.com/34033913/69334875-ed3d5b80-0c5b-11ea-9537-7ef928154548.gif)

**Comment by jtpio** [comment]
Actually it looks this is coming from core JupyterLab. Testing in a different environment with JupyterLab 1.2.3 with the following code and the default kernel (not xeus-python):

```python
import time
time.sleep(10)
```

![kernel-future-disposed-widget](https://user-images.githubusercontent.com/591645/69441672-6b2c6000-0d4b-11ea-9985-06fb318f681c.gif)

**Comment by jtpio** [comment]
I will check if this is tracked in the JupyterLab repo. This is related to the `execute_request` flow.

In the meantime we should be able to close this issue.
