### ISSUE TITLE
Add a interface for Debugger.Model

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/debugger#218]
Currently IDebugger exposes the Debugger.Model class in its API while it should expose an interface only.

**Comment by jtpio** [comment]
I think that refers to this TODO: 

https://github.com/jupyterlab/debugger/blob/30d0da7b577786900bc390ae91468aff39a99ab7/src/tokens.ts#L16-L19

**Comment by JohanMabille** [comment]
Indeed!
