### ISSUE TITLE
Drop main area widget completely

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/debugger#229]
Following an in-person discussion with @jtpio, we feel that the main area widget feels a bit weird compared to the side panel, notably because of the nested tabs.

A change that would allow to completely drop the main area mode, and show the current position in the code in the side panel as in the following mock up:

![DEBUGGER_LAYOUT](https://user-images.githubusercontent.com/2397974/69556492-15eb8b00-0fa5-11ea-8566-816dca03ab74.png)

The button in the CODE section of the split panel would be used to open that file in a new tab of the main area widget should the user want it. The CODE section of the side panel would always only show the current position in the call stack. We could even decide to make it *not* scrollable...

This is related to #176

**Comment by SylvainCorlay** [comment]
cf #176

**Comment by jtpio** [comment]
Yes, #176 also proposes to keep only one mode (sidebar / condensed).

Other IDEs also implement this idea of a temporary view, instead of opening new files every time.

Should we move the discussion to #176?

**Comment by SylvainCorlay** [comment]
OK, closing. Moving my comment there.
