### ISSUE TITLE
Should IDebugger be an IDisposable?

### ISSUE THREAD

**Issue by afshin** [jupyterlab/debugger#235]
`IDebugger` is the public token that other plugins can import. Is there a use case for a consumer of `IDebugger` having the ability to call `IDebugger#dispose()`? It seems like that should not be part of the public interface.

**Comment by jtpio** [comment]
This probably started to be the case when the `DebugService` changed to the an `IDebugger`.

I don't see any use case for a `dispose`, so we can remove it from the public interface :+1:
