### ISSUE TITLE
Allow creating and deleting breakpoints in out-of-focus cells

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/debugger#238]
At the moment, adding a breakpoint to a notebook cell requires it to have focus.

I think that it would make sense to always allow for adding breakpoints to any cell.

**Comment by jtpio** [comment]
This would require:

- creating an `EditorHandler` for each cell of the notebook when the notebook handler is created
- remove the call to `dispose` when the active cell is changed: 

https://github.com/jupyterlab/debugger/blob/9367c70bfceaa5b0a3bb9446d1d2310503821da4/src/handlers/notebook.ts#L69

- keep a `cellMap` (`Map` or `ObservableMap`) of cell.id -> `EditorHandler`
- create a new editor handler when a new cell is create
- dispose the editor handlers when the notebook is disposed
