### ISSUE TITLE
[UX] Show Source Path

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/debugger#253]
Given that the source may not point to the active file, I suggest adding a file path to the source heading. See attached image
![Debugger source](https://user-images.githubusercontent.com/22109376/70272756-69f92b00-176e-11ea-987b-b76532589d2c.png)

**Comment by jtpio** [comment]
Should we drop the `text-transform: uppercase`? I think it was set in the beginning so it looks similar to the palette and running tab:

![image](https://user-images.githubusercontent.com/591645/70314311-81402300-1817-11ea-89e6-159d7437dcd0.png)

**Comment by afshin** [comment]
Yeah, I think we should drop that style because semantically it's different from the sub-headings of the command palette.
