### ISSUE TITLE
Step into non-user code

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#263]
It is possible to step into a local module just fine (https://github.com/jupyterlab/debugger/pull/248). But stepping into non-user code such as the standard library or third-party libraries will give something like the following:

![step-in-stdlib](https://user-images.githubusercontent.com/591645/70513673-5d8c1e00-1b32-11ea-9774-94830b5f0236.gif)

Note that the behavior is similar in VS Code when `justMyCode` is set to `true` in the launch configuration:

![step-in-stdlib-vscode](https://user-images.githubusercontent.com/591645/70513338-b8714580-1b31-11ea-95ce-98f16e21da10.gif)

After some investigation, it seems that `justMyCode` is passed at `launch`. Also this parameter is not part of the DAP.

We should check whether we can make use of this parameter with the interactive mode.

**Comment by dbalabka** [comment]
It pretty often cases when you are required to investigate vendor library sources during a debugging session. For me, it is the most frequent use case.

**Comment by JohanMabille** [comment]
Notice that in the context of Jupyter, there is no Launch request since the interpreter is always running.

**Comment by jnarula5** [comment]
Hi Jeremy,

Can you please point me to the code where justMyCode needs to be set to False?

Thanks,
Jaspreet

**Comment by jtpio** [comment]
Last time we investigated this, `justMyCode` was not part of the DAP and it seemed like it would require a couple of changes in xeus-python and / or the debugger extension.

**Comment by hsinhungli** [comment]
I just started trying to use the Jupyter debugger, and run into the same issue. I feel that this is the most needed function in my application. That is, stepping into the functions that are loaded from existed modules or library stored in other folders on my computer. I wonder whether this is issue has been resolved. Based on the previous message, there is still no work around (e.g., justMyCode) for this? Is that correct?

**Comment by JohanMabille** [comment]
If I remember correctly, passing this paramete was required to get PTVSD break into user code (but that is pure cargo-culting, I did nt investigate more). I can test again now that the debugger has migrated to debugpy.

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/pull/11566 and https://github.com/ipython/ipykernel/issues/811

**Comment by echarles** [comment]
Thx @jtpio for the backlink. This discussion is interesting.
