### ISSUE TITLE
[Variable Inspector] Switch back to table view?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#272]
I was showing the state of the debugger to someone currently using Spyder instead of Jupyter notebooks. The feedback was that the tree view didn't feel as intuitive as the table view in Spyder to inspect variables.

Maybe we should switch back to a table view instead of a tree view? For reference this is what it looks like in Spyder:

![spyder-variable-explorer](https://user-images.githubusercontent.com/591645/70617111-27bd6700-1c10-11ea-9c2a-177753c0cbc2.gif)

This could have some benefits:

- The table view is a more familiar interface for users that are not necessarily developers
- Double-clicking on a variable (for example when inspecting a nested dictionary or a numpy array) could create a new table with the new content. A "back arrow" would bring back to the top-level view  
- For widgets: hovering on the value in the table would bring a popup with the rendered (and interactive) widget
- It would also be easier to detect when a new `variables` debug request must be sent to the kernel

**Comment by afshin** [comment]
I think this is a good idea, because as we talked about on yesterday's call, our "tree" really is only one level deep anyway. The main benefit of the tree is collapsing the `local` vs. `global` variables, but perhaps that can just be two tables.

**Comment by jtpio** [comment]
Two tables sounds good (or one table per `scope` to stick to the DAP).

Also this would make it convenient to edit variables on the fly, for example by double-clicking on a cell in the table, and using the [`evaluate` request from the DAP](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) to send the new value.

**Comment by dhirschfeld** [comment]
> *Double-clicking on a variable (for example when inspecting a nested dictionary or a numpy array) could create a new table with the new content. A "back arrow" would bring back to the top-level view*

...or the popup could have the tree-view of the object. Not everything maps well to a 2D table and for custom classes I really like the ability to expand the object to introspect objects that aren't in the repr

**Comment by dhirschfeld** [comment]
For ref, the variable inspector in PyCharm is a tree-view which I quite like - I guess it's what you're used to

![image](https://user-images.githubusercontent.com/881019/70667798-8856ad80-1cbd-11ea-970e-6905edfbb6e3.png)

**Comment by jtpio** [comment]
Thanks @dhirschfeld. A tree can be more natural for a structure like a `class` or a `dict`.

It looks like PyCharm also has a `View As Array` that opens a `numpy` array as a table.

**Comment by afshin** [comment]
cc: @tgeorgeux This is an are that could really use some UX love. The question is, what's a good way for us to show the list of variables in a context and how do we show those variables to users when they want more details?

**Comment by tgeorgeux** [comment]
Is there any reason we couldn't support a table and a tree view? I can design a nice little toggle that switches between views. 

I don't have much experience using debuggers, but it looks like we have good examples of why each is helpful above.

**Comment by afshin** [comment]
We could have both, but I'd suggest we think a little bit about how JupyterLab isn't really an "integrated development environment" and is more of an "integrated data environment" and think about a user interface that takes advantage of the ecosystem lab is in.

One idea that came up in today's debugger call is something a bit like the Spyder screenshots above, maybe taking advantage of that same panel that we use to show the breakpoint snippet and allowing users to pop them out into their own tabs.

We are trying to target version 0.2 to come out some time near the end of January, beginning of February, a few weeks after JupyterLab 2.0 ... and hopefully part of that release will be improving the variable view.

@tgeorgeux Can you or a designer working with you put some time into a user experience and design for this feature in time for us to implement it for that release? I understand if that timeframe is too ambitious given your other constraints.

**Comment by dhirschfeld** [comment]
To be clear, I think a table view with a (truncated? or custom?) repr is fine for a first cut.

After that, what would be great is to be able to double-click to bring up either a default json tree-view "object inspector" which you could explore by expanding attributes. For certain objects e.g. arrays/dataframes double-clicking could bring up a custom viewer such as data-grid instead.

**Comment by KsavinN** [comment]
@tgeorgeux  Hi, Did you find some time to design for this feature. I know that probably you are busy :)

**Comment by jtpio** [comment]
@KsavinN how about starting with something like the following?

![variables-table-view-jupyterlab](https://user-images.githubusercontent.com/591645/72439303-f6076500-37a6-11ea-8f5e-394c53f2b31b.png)

Or maybe draw some inspiration from https://github.com/lckr/jupyterlab-variableInspector.

Wondering whether we could use `@lumino/datagrid` to display the variables. Although we might be limited when it comes to editing the values or defining click handlers (but there is some work in progress in https://github.com/jupyterlab/lumino/pull/14).
If not for top-level variables then it could be used to display data frames or numpy arrays.

**Comment by jtpio** [comment]
Spent some time today prototyping support for ipywidgets for the [jupyterlab-variableInspector](https://github.com/lckr/jupyterlab-variableInspector) extension:

![widget-support](https://user-images.githubusercontent.com/591645/72561733-1b30cc00-38aa-11ea-874b-95d01268c21d.gif)

Maybe we can have something similar for the variable inspector of the debugger too (in some later version).

One thing to keep in mind though is that interacting with widgets triggers requests sent to the `shell` channel (ending up being queued), which will not be processed when the execution has stopped (breakpoint hit).

**Comment by KsavinN** [comment]
@jtpio  that looks really intresting

**Comment by SylvainCorlay** [comment]
@jtpio this looks cool.

1. We may want to disable the interaction of widgets in the inspector to not stack many comm messages that would not be processed as shell is blocked.

2. More generally, enabling mime type rendering will be really cool, but I would do it outside of the table view, so that we can display larger things such as figures, tables, etc...

**Comment by jtpio** [comment]
@SylvainCorlay this is actually now merged and available in the `jupyterlab-variableInspector` extension, see https://github.com/lckr/jupyterlab-variableInspector/pull/125.

Otherwise yes, those are valid points. Especially if we start relying on the Lumino data grid (https://github.com/jupyterlab/debugger/pull/369#issuecomment-594065552) to display the variables.

**Comment by jtpio** [comment]
Closing this, as the table view has been implemented. 

We can iterate on it and report issues separately (https://github.com/jupyterlab/debugger/issues/388 for example).
