### ISSUE TITLE
Handle session path changed

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#294]
At the moment we don't handle session path changes, for example when a notebook is renamed:

![session-path-changed](https://user-images.githubusercontent.com/591645/70913021-7a828e80-2015-11ea-9297-d0e981d1ac79.gif)

We can however change the focus on the current widget to reinitialize the state, which seems to be picked up by the handlers.

**Comment by KsavinN** [comment]
Maybe for Set of clients, we can use Id of the kernel. I guess user cant change that.

**Comment by jtpio** [comment]
Let's have another look at that when we start targeting JupyterLab 2.0, which includes a rework of the kernel and session management.
