### ISSUE TITLE
Make the ILabShell dependency optional

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#312]
*Originally suggested by @afshin*.

In some of the plugins `ILabShell` is required as a dependency, mostly so the `labShell.currentChanged` signal can be used.

We should instead make this an optional dependency and make use of the `currentChanged` signal only when `ILabShell` is provided.

This will make it easier to reuse the debugger in other frontends that don't have the notion of multiple widgets for example.

**Comment by KsavinN** [comment]
_after discussion_

ILabShell will be optional but all plugins of debugger should have required own tracker like plugin for notebookHandler should have required notebooktracker..

**Comment by jtpio** [comment]
Fixed by #335.
