### ISSUE TITLE
Hide some variables from the variables pane

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/debugger#314]
Some variables in the scope like `ptvsd` or `_ptvsd_stop_at_break` could/should be hidden from the user? I wonder if this should be the back-end's or the front-end's responsibility though.

**Comment by jtpio** [comment]
Good question.

These variables actually live in the kernel, so it's kind of "correct" to see them in the variable explorer:

![image](https://user-images.githubusercontent.com/591645/71247061-44e0ec80-2318-11ea-92c7-283f28f9186e.png)

Probably the simplest option would be to add a filter in the advanced settings, containing `ptvsd`, `_ptvsd_stop_at_break` and others by default.

Users who still want to see these variables could go to the settings and remove the filter. They could also add other variables they want to have filtered out.

Also there was a similar issue (#179) about filtering private variables. Maybe we could move the conversation there?

**Comment by martinRenou** [comment]
> so it's kind of "correct" to see them in the variable explorer

It sure is correct. The thing is we might not want to user to "mess up" with ptvsd's API.. I don't know how much control he would have on the debugger though.

Sorry I did not see this other issue on filtering variables. I will close this one.
