### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by MaverickMeerkat** [jupyterlab/debugger#328]
PS C:\Users\david> jlpm build
yarn run v1.15.2
error Couldn't find a package.json file in "C:\\Users\\david"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

am I suppose to be in a specific directory?

**Comment by jtpio** [comment]
@MaverickMeerkat it looks like you are trying to install from source.

How about installing the released version instead? With:

`jupyter labextension install @jupyterlab/debugger`

**Comment by MaverickMeerkat** [comment]
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\david\\Anaconda3\\share\\jupyter\\lab\\staging\\linked_packages\\jupyterlab-application-top-1.2.3-519ecff849ccc98b6b8c6d75d24dd8f27c3583cd.tgz'

**Comment by jtpio** [comment]
Thanks @MaverickMeerkat for trying it out.

The debugger extension enables debugging only for the `xeus-python` kernel for now, which is not (yet) available on Windows.

Maybe using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) could be a solution in the meantime (cf [this blog post](https://medium.com/hugo-ferreiras-blog/using-windows-subsystem-for-linux-for-data-science-9a8e68d7610c))?

**Comment by eyaltrabelsi** [comment]
@jtpio  I have issues on mac as well installation takes forever and never finish,  can you share lights on this?

**Comment by jtpio** [comment]
@eyaltrabelsi are you referring to this issue? https://github.com/jupyterlab/debugger/issues/390

**Comment by eyaltrabelsi** [comment]
@jtpio Nope #390 was on ubuntu server and now working, on mac os the conda command simply never finish

**Comment by eyaltrabelsi** [comment]
@jtpio bump

**Comment by afshin** [comment]
Please run these commands. If they work, you're set. If they do not, please paste everything that it outputs to help us see what is happening.

```
conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.6.12 notebook=6 ptvsd jupyterlab=2
conda activate jupyterlab-debugger
jupyter labextension install @jupyterlab/debugger
```

**Comment by afshin** [comment]
@eyaltrabelsi @MaverickMeerkat If you are still having issues after trying the commands above, please open a new issue! Good luck.

**Comment by Ferdie-data27** [comment]
@afshin here's the 'output'i got ...

satorusotoyama@Satorus-MacBook-Pro ~ % conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.6.12 notebook=6 ptvsd jupyterlab=2
conda activate jupyterlab-debugger
jupyter labextension install @jupyterlab/debugger
zsh: command not found: conda
zsh: command not found: conda
zsh: command not found: jupyter
satorusotoyama@Satorus-MacBook-Pro ~ % 

Could you please help me what to do with this issue?

**Comment by JohanMabille** [comment]
You need download and install [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/download.html) first
