### ISSUE TITLE
Use a released version for the stable Binder

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#330]
Now that `0.1.0` was released, we could use it as the stable Binder, instead of building the extension from source.

For the `master` branch Binder (which installs the extension from source), we could:

- drop it
- keep `stable` one commit ahead of master, and rebase for each new release (might require slightly more manual manipulations)

**Comment by afshin** [comment]
Maybe for the near-future we don't even need a stable branch any more because we can just release pre-releases/alphas/betas frequently enough that we can always install from NPM.

**Comment by jtpio** [comment]
The `stable` branch is mostly useful to avoid triggering new builds on mybinder.org, and use a built image if it already exists.

And yes the content of the `postBuild` file would be replaced by something like this:

```
jupyter labextension install @jupyterlab/debugger@0.1.0
```

**Comment by afshin** [comment]
I meant something more like `jupyter labextension install @jupyterlab/debugger@latest` ... are you concerned that that might be too unstable?

**Comment by jtpio** [comment]
Not really concerned about the stability of the extension.

It's more that if we choose to go for `jupyter labextension install @jupyterlab/debugger@latest`, then the Binder link must point to `master`, so a new Binder can be built and install the latest version of the extension.

A `stable` branch (other names also welcomed) helps making the Binder launch faster.

**Comment by afshin** [comment]
If the branch is primarily for binder and not semantically equivalent to stability, then maybe it should just be the `binder` branch?

**Comment by SylvainCorlay** [comment]
> If the branch is primarily for binder and not semantically equivalent to stability, then maybe it should just be the binder branch?

yeah - although we have been using that pattern (calling the branch stable) for a bunch of repositories already.

**Comment by jtpio** [comment]
And the `stable` branch usually points to the latest stable version / tag.

**Comment by afshin** [comment]
Fair enough, then. That makes sense to me 👍
