### ISSUE TITLE
kernel with support for debugging is also required to be able to use the debugger:

### ISSUE THREAD

**Issue by sidsidsidsid** [jupyterlab/debugger#342]
Any help would be appreciated. 

I'm having an issue with this extension. First, I do not see it in the extension manager. I assume this is considered a pre-release and not available as of yet.

So, I went to the git location and read the manual instructions. Below, is the issue I'm having.

step1: 
open a terminal via the anaconda navigator for my particular environment

step2:
 enter the below command and everything appear successful.:
"...jupyter labextension install @jupyterlab/debugger"

step 3:
I can see the extension/debugger in the notebook, but it appears not to be working. I cannot add breakpoints and etc.. In the demo on the git site, there is a switch in the right corner of the notebook, near the kernel indicator, this is not showing up.

step 4:
I went back to the instructions and noticed I didn't execute the below command in the terminal
"....conda install -c conda-forge xeus-python=0.6.7 notebook>=6 ptvsd...."

step 5:
After entering the above command, the terminal just stalls. I have started and stopped the anaconda navigator several times, but the same issue continues. I get no response after entering the command.

**Comment by afshin** [comment]
Can you try doing them line by line to see which thing fails?
```
conda create -n test-debugger python=3.7
conda activate test-debugger
conda install -c conda-forge jupyterlab
conda install -c conda-forge ptvsd
conda install -c conda-forge xeus-python
jupyter labextension install @jupyterlab/debugger
```
This way you can report back which one of those commands fails and paste the error.
