### ISSUE TITLE
Wrong behavior of lifecycle debugger

### ISSUE THREAD

**Issue by KsavinN** [jupyterlab/debugger#351]
![wrongLifebehav](https://user-images.githubusercontent.com/34033913/72898770-febae680-3d24-11ea-9667-f0aed984518a.gif)

**Comment by jtpio** [comment]
To give a bit more context: when we switch to a kernel that has support for debugging, but the debug button is switched off, we should still be able to see the debug data from the other notebook in the sidebar.

This means changing the handler logic around here: https://github.com/jupyterlab/debugger/blob/ce99123a5f01675aba300565d6532bcd0e075964/src/handler.ts#L232
