### ISSUE TITLE
Cannot see xpython kernel in jupyter lab

### ISSUE THREAD

**Issue by davidlee321** [jupyterlab/debugger#365]
Hi there.

I've installed this debugger extension, togther with the needed packages (xeus-python, ptvsd), `jupyter lab build`. I can see the debugger button in jupyter lab. Clicking this button brings up a sidebar with panels named variable, callstack, breakpoints, source (as seen in the .gif animation in the `README.md`). At this stage I am not in a "xpython kernel".

According to what I've read, this extension can, at the moment, only work in a xpython kernel. However, I don't see how to use an xpython kernel in jupyter lab :(

Much thanks for helping me.

**Comment by martinRenou** [comment]
Hello!

If I understand your question correctly, you simply need to change the current kernel that is used. See the following gif:

![switchkernel](https://user-images.githubusercontent.com/21197331/75134422-8f973000-56de-11ea-9f69-6dc0866b30e7.gif)

**Comment by jtpio** [comment]
Alternatively, `xeus-python` should also show up in the launcher:

![image](https://user-images.githubusercontent.com/591645/75235047-f8080f00-57bb-11ea-80c1-d422b9ff4ad4.png)

**Comment by shukyp** [comment]
The problem is that it doesn't appear on the list (after successful installation)
