### ISSUE TITLE
After installing xeus-python

### ISSUE THREAD

**Issue by curieuxjy** [jupyterlab/debugger#380]
Hello :)
After installing xeus-python using this code
`conda install -c conda-forge xeus-python=0.6.7` , 
I command `jupyter lab` on the anaconda prompt.
And I received `ModuleNotFoundError: No module named 'jupyter_server'`.
Also when I command `jupyter notebook`, 
I received `ImportError: DLL load failed while importing error:`
How can I solve this problem?

**Comment by curieuxjy** [comment]
I make a virtual env for xeus-python and solve the problem!
so it is closed. :)

**Comment by SylvainCorlay** [comment]
> ImportError: DLL load failed while importing error

The version of pyzmq shipped with the anaconda distribution is incompatible with that of conda-forge.

Installing from a miniconda or forcing the pyzmq version from conda-forge should fix the issue.
