### ISSUE TITLE
how i can install debbuger without conda(only with pip)?

### ISSUE THREAD

**Issue by Zawarud** [jupyterlab/debugger#387]
how i can install debbuger without conda(only with pip) in windows?

**Comment by martinRenou** [comment]
xeus-python cannot be installed with pip yet. See https://github.com/jupyter-xeus/xeus-python/issues/181. But this feature is coming soon.

**Comment by Zawarud** [comment]
im waiting for this. Ty for answers.

**Comment by SylvainCorlay** [comment]
@Zawarud the work to package it for PyPI is happening in https://github.com/jupyter-xeus/xeus-python-wheel.
