### ISSUE TITLE
Implement layout restoration as outlined in design document.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/debugger#39]
Instead of always restoring to a sidebar, restoration should support either creating a `MainAreaWidget<Debugger>` or just the sidebar. This issue is dependent on https://github.com/jupyterlab/debugger/issues/38 first.

**Comment by jtpio** [comment]
The layout restoration was implemented in https://github.com/jupyterlab/debugger/pull/54.

![layout-restoration](https://user-images.githubusercontent.com/591645/67019354-ce97f200-f0fc-11e9-95fa-483eeaf381db.gif)
