### ISSUE TITLE
Not Working with new  conda/virtualenv 

### ISSUE THREAD

**Issue by eyaltrabelsi** [jupyterlab/debugger#390]
I can't find anywhere how can I enable new "xpython virtualenv" ?

**Comment by JohanMabille** [comment]
Not sure to understand your problem, to create a new environment and install xeus-python and the debugger:

```bash
conda create -n my_new_env
conda activate my_new_env
conda install  xeus-python=0.6.12 notebook=6 jupyterlab ptvsd -c conda-forge
jupyter labextension install @jupyterlab/debugger
```

**Comment by eyaltrabelsi** [comment]
@JohanMabille The way I worked is I installed debugger in the following way:
> conda install  xeus-python=0.6.12 notebook=6 jupyterlab ptvsd -c conda-forge
> jupyter labextension install @jupyterlab/debugger

Now if i construct new conda like you showed:
> conda create -n my_new_env
> conda activate my_new_env

**My problem is that after executing this  xpython-my_new_env wont show in the list of existing envitonments.**

Do i need to specify the xeus-python in the conda creation itself? If not what may be the problem?

**Comment by JohanMabille** [comment]
I don't understand why you expect to see an environment called "xpython-my_new_env". Are you talking about conda environments? If so the only environment you see are those you create, and you didn't create any `xpython-my_new_env`

**Comment by eyaltrabelsi** [comment]
@JohanMabille ok understood , what command do I need to run in order to create a  newconda environment that will be with xpython interperter and will be listed in jupyter notebook

**Comment by JohanMabille** [comment]
Ok I think I understand your confusion now. So `xpython` is not a python interpreter, it is a Jupyter kernel for Python. It makes use of the Python interpreter already installed in your environment.

After you run the commands from my first answer, launch a notebook, click on new, you should be able to select `xpython`.

Notice that the debugger is supported with JupyterLab only, not with the classical notebook.

**Comment by eyaltrabelsi** [comment]
@JohanMabille 
I am still confused because I would expect to see each conda environment both in python kernal ( I see all conda environments) and the xpython kernal (I see only the basic one).

Does this mean that xpython hold only the conda environment that is activated

**Comment by JohanMabille** [comment]
> I would expect to see each conda environment both in python kernal ( I see all conda environments) 

Can you post a screenshot please? This sentence does not make any sense for me. `xpython` does not hold any environment, it's just a Jupyter kernel, that can be installed in a conda environment (like any other Jupyter kernel), like any other Jupyter kernel.

**Comment by eyaltrabelsi** [comment]
@JohanMabille 
<img width="1091" alt="Screen Shot 2020-03-11 at 14 38 57" src="https://user-images.githubusercontent.com/19736629/76417980-84aef180-63a6-11ea-8856-ca46342b75bf.png">

As you can see I have 2 conda environments:
* root
* research

I would expect to have xpython: env:research in addition to the root one

**Comment by JohanMabille** [comment]
Ok so actually I think that you have installed ipython in both environment (root and research), while you installed `xpython` in the root environment only. If you want to see `xpython [env:research]`, you need to install `xpython` in the research environment too.

**Comment by eyaltrabelsi** [comment]
@JohanMabille cool so its work now, so I need to install xpython + conda debugger for each environment and then it works.

Thanks again

**Comment by JohanMabille** [comment]
You're welcome!

**Comment by jtpio** [comment]
Closing as answered.

Thanks both @eyaltrabelsi and @JohanMabille!
