### ISSUE TITLE
Toggle button visibility - not displaying on tab.

### ISSUE THREAD

**Issue by sidsidsidsid** [jupyterlab/debugger#402]
I installed this extension in JupyterLab. The enable toggle button is not displaying in the right/top of the notebook tab. The far-right debug sidebar is visible, but not the toggle button on the tab.

I restarted jupyterLab, but still, the issue persists.

Is there any instructions and/or documentation on how to interact with the extension. Or notes if additional dependencies are required.

This is slightly different than the other issues with the toggle. In those issues, the toggle does get displayed.

thanks

**Comment by KsavinN** [comment]
Hi @sidsidsidsid , did you run notebook with xeus-python?  You can change kernel and check if you have in jupyterlab xeus-python in that way:
![help](https://user-images.githubusercontent.com/34033913/77404422-fed17400-6db1-11ea-9218-c2eb21e39e91.gif)

**Comment by jorijnsmit** [comment]
Had the same issue, was indeed not using `xpython` as the kernel.

**Comment by eyaltrabelsi** [comment]
@KsavinN I had the same issue of toggle button visibility

**Comment by KsavinN** [comment]
@sidsidsidsid  Is your issue still exist? If yes, could you write more details or send a screenshot?

**Comment by sidsidsidsid** [comment]
I'm attempting to test your solution, but when installing the kernel it gave me errors. 

=================================ERROR=================
$>conda install xeus-python notebook -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound:
  - defaults/win-64::setuptools==40.2.0=py35_0
  - defaults/win-64::lxml==4.2.5=py35hef2cd61_0
  - defaults/win-64::pyopenssl==18.0.0=py35_0
  - defaults/win-64::sqlalchemy==1.2.11=py35hfa6e2cd_0
  - defaults/win-64::cffi==1.11.5=py35h74b6da3_1
  - defaults/win-64::six==1.11.0=py35_1
  - defaults/win-64::markupsafe==1.0=py35hfa6e2cd_1
  - defaults/win-64::win_inet_pton==1.0.1=py35_1
  - defaults/win-64::wheel==0.31.1=py35_0
  - defaults/win-64::pytables==3.4.4=py35he6f6034_0
  - defaults/win-64::urllib3==1.23=py35_0
  - defaults/win-64::scipy==1.1.0=py35hc28095f_0
  - defaults/win-64::asn1crypto==0.24.0=py35_0
  - defaults/win-64::pysocks==1.6.8=py35_0
  - defaults/win-64::cython==0.28.5=py35h6538335_0
  - defaults/win-64::cryptography==2.3.1=py35h74b6da3_0
  - defaults/win-64::matplotlib==3.0.0=py35hd159220_0
  - defaults/win-64::idna==2.7=py35_0
  - defaults/win-64::qt==5.9.6=vc14h1e9a669_2
  - defaults/win-64::patsy==0.5.0=py35_0
  - defaults/win-64::pip==10.0.1=py35_0
  - defaults/win-64::statsmodels==0.9.0=py35h452e1ab_0
  - defaults/win-64::networkx==1.11=py35_1
  - defaults/win-64::sqlite==3.30.1=he774522_0
  - defaults/win-64::bottleneck==1.2.1=py35h452e1ab_1

**Comment by SylvainCorlay** [comment]
@sidsidsidsid I recommend using a new conda environment. Your root env probably includes some package pinning that prevent conda from installing this package.

**Comment by jorijnsmit** [comment]
Yes this was my issue as well, `xeus-python` could not be installed into my root env because of package incompatibilities.

Just follow the [README instructions](https://github.com/jupyterlab/debugger) and you'll be fine:
```
conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.6.12 notebook=6 jupyterlab=2 ptvsd
conda activate jupyterlab-debugger
```
Then, run the following command to install the extension:
```
jupyter labextension install @jupyterlab/debugger
```

**Comment by sidsidsidsid** [comment]
ALL, it's working now. Thanks, for the assistance.

**Comment by jtpio** [comment]
Thanks @sidsidsidsid and @jorijnsmit for getting back!

Closing as answered.
