### ISSUE TITLE
DOC: README: add link to and from medium article

### ISSUE THREAD

**Issue by westurner** [jupyterlab/debugger#407]
- [ ] DOC: README: add link to medium ANN article 
  https://blog.jupyter.org/a-visual-debugger-for-jupyter-914e61716559
- [x] DOC: Article: add link to this repo:
  https://github.com/jupyterlab/debugger
- [x] DOC: update gh project desc?

  "a JupyterLab debugger extension [for debugging code in Jupyter notebook cells]"

**Comment by SylvainCorlay** [comment]
> DOC: README: add link to medium ANN article

I don't know about that. READMEs are supposed to be up to date while blog posts are a point-in-time thing.

> DOC: Article: add link to this repo:

DONE!

> "a JupyterLab debugger extension [for debugging code in Jupyter notebook cells]"

It also works with

**Comment by westurner** [comment]
So the blog post is the docs?

The way it reads I think it's for debugging Jupyter itself

>

**Comment by SylvainCorlay** [comment]
> So the blog post is the docs?

I meant that we cannot include links to blog posts in the docs or readme because the blog post will soon be out of date as the software changes, while we keep the docs up to date.

> The way it reads I think it's for debugging Jupyter itself.

Yep, we should probably update the description!

**Comment by jtpio** [comment]
The README and description have now been updated.

Should we consider this fixed? Or do we want to link to the blog post too?

**Comment by afshin** [comment]
I think this is good, blog post half-life is short. Let's call this one fixed.

**Comment by westurner** [comment]
Thanks!
