### ISSUE TITLE
Debugger hangs and becomes unresponsive

### ISSUE THREAD

**Issue by SirSharpest** [jupyterlab/debugger#411]
On OSX everything works fine with this xpython kernel, except for debugging (and widget displays, but that's another issue, so shan't detail here). 

I installed via the following commands: 

```
conda install xeus-python -c conda-forge
jupyter labextension install @jupyterlab/debugger
```

I'm running on `Python 3.6.10 :: Anaconda, Inc.`

Upon running a blank `.ipynb` file I add the following:

```
a = 5
b = 10 
```

I then click debugging and observe nothing, the terminal I ran jupyter-lab from shows:

```
Run with XEUS 0.23.9
XEUS-PYTHON: the debugger has started
XEUS-PYTHON: dumped /var/folders/lx/djqs79z111382xk8wsr32p300000gn/T/xpython_20204/1036597689.py
```

The JupyterLab window will produce no output, set my CPU to 100% and do nothing until the kernel is halted. 

I can provide any other information which would be useful, or possibly a screencast of my process if it would be helpful.

**Comment by martinRenou** [comment]
> and widget displays, but that's another issue, so shan't detail here

Would you mind opening an issue on [xeus-python](https://github.com/jupyter-xeus/xeus-python) for that? Maybe we can tackle your issue before the next release

**Comment by SirSharpest** [comment]
Sure, done: https://github.com/jupyter-xeus/xeus-python/issues/224

**Comment by SylvainCorlay** [comment]
Closing here as this is more of a xeus-python thing.
