### ISSUE TITLE
xpython kernel does not execute tsfresh functions

### ISSUE THREAD

**Issue by theinem** [jupyterlab/debugger#412]
I have installed Jupyter lab debugger in my windows 10. 

I have followed explanation in: https://blog.jupyter.org/a-visual-debugger-for-jupyter-914e61716559

It was working ok. Now I'm executing tsfresh's function "extract_features", who works in python 3 kernel, but it doesn't in xpython kernel.

I let the code and the execution in both kernels.

```
from tsfresh import extract_features
settings = {'abs_energy': None,
            'standard_deviation': None,
            'absolute_sum_of_changes': None, 
            'number_crossing_m': [{'m': 0}]}
extracted_features = extract_features(DB.drop('Labels', axis=1), column_id="id", column_sort="time", default_fc_parameters=settings)
...
```

![reporteXPython1](https://user-images.githubusercontent.com/18086414/77854951-ed71d880-71b2-11ea-8818-3bc9f9b05af0.png)
![reporteXPython2](https://user-images.githubusercontent.com/18086414/77854953-eea30580-71b2-11ea-9ecf-914de2943280.png)

**Comment by jtpio** [comment]
Thanks @theinem for reporting the issue.

Is this happening with the debug toggle button turned on or off?

![image](https://user-images.githubusercontent.com/591645/77886210-bc53df80-7268-11ea-8822-3b73fca212ce.png)

**Comment by jtpio** [comment]
Ah I see there is already an issue on the `xeus-python` repo there: https://github.com/jupyter-xeus/xeus-python/issues/230

Let's close this one then to keep the conversation in one place.
