### ISSUE TITLE
Connect to the debugger

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#42]
Now that there is a minimal UI for the debugger, we could start using the `DebugSession` to send debug requests to the kernel and have a "loop" in place:

- start the debugger
- initialize (set config and breakpoints)
- request scopes and variables
- stop the debugger

**Comment by jtpio** [comment]
How about we add the `start` and `stop` buttons in the Debugger `MainAreaWidget` for now?

(while we figure out whether to automatically start the debugger or not)

**Comment by jtpio** [comment]
cc @afshin @KsavinN

**Comment by KsavinN** [comment]
What about in the sidebar and right-click menu?

**Comment by jtpio** [comment]
With the `app.contextMenu`? That would be fine too.

**Comment by jtpio** [comment]
I would say the idea is to have them somewhere so we can send the debug commands. And we can move them (or remove) somewhere else later on.

**Comment by jtpio** [comment]
Connecting to the debugger was added in https://github.com/jupyterlab/debugger/pull/47.

The other points have their own issues (https://github.com/jupyterlab/debugger/issues/43 and https://github.com/jupyterlab/debugger/issues/44), so we can close this one.
