### ISSUE TITLE
ptvsd isn't listed as a dependency

### ISSUE THREAD

**Issue by evamvid** [jupyterlab/debugger#420]
It's a dependency, but it's not listed anywhere as such that I can see.

**Comment by afshin** [comment]
It is listed in the installation instructions:

> ## Installation
> 
> A kernel with support for debugging is required to be able to use the debugger.
> 
> It is generally recommended to create a new `conda` environment to install the dependencies:
> 
> ```bash
> conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.6.12 notebook=6 jupyterlab=2 ptvsd
> conda activate jupyterlab-debugger
> ```
> 
> Then, run the following command to install the extension:
> 
> ```bash
> jupyter labextension install @jupyterlab/debugger
> ```

https://github.com/jupyterlab/debugger#installation

**Comment by jtpio** [comment]
Closing as answered.

@evamvid don't hesitate to comment here if you have any questions.
