### ISSUE TITLE
can't handle magic commands

### ISSUE THREAD

**Issue by mdmmn378** [jupyterlab/debugger#421]
The debugger can not differentiate magic commands as stand-alone jupyter lab does.
![image](https://user-images.githubusercontent.com/26161844/78844484-b491f900-7a27-11ea-9012-b62638adcf11.png)

**Comment by afshin** [comment]
Hello! The debugger currently works with the `xeus-python` kernel, which does not yet support magics.

Debugging magics is an interesting question in itself, which we can approach after `xeus-python` supports them.

**Comment by mdmmn378** [comment]
Thanks for your prompt answer. 
Ya, I think it will be a great feature. But for now, skipping the magic lines will do.

**Comment by jtpio** [comment]
Closing, as this is being tracked in multiple issues in the `xeus-python` repo:

- https://github.com/jupyter-xeus/xeus-python/issues/224
- https://github.com/jupyter-xeus/xeus-python/issues/63
