### ISSUE TITLE
Extention doesn't work

### ISSUE THREAD

**Issue by turovapolina** [jupyterlab/debugger#422]
Dear all,

I am really sorry to disturb you but I installed a debugger according to all your recomendations on the main page (with new envinroment) but after running my code I still don't see any variables on the right panel:
![image](https://user-images.githubusercontent.com/61549119/79261742-f3490880-7e98-11ea-9f74-6460165a3264.png)
And as I see on the left panel the extention is enabeled.
Could you please clarify how I can use debugger properly? 

Best regards,
Polina

**Comment by SylvainCorlay** [comment]
This notebook does not run the xpython kernel. You need to switch the kernel from "Python 3" to xpython.

**Comment by turovapolina** [comment]
> This notebook does not run the xpython kernel. You need to switch the kernel from "Python 3" to xpython.

Thank you very much!

**Comment by tinyxuyan** [comment]
Does it mean that I can only use the debugger when selecting xeus-python kernel? I am wondering whether I can switch to other preinstalled kernel to use the debugger. I have installed some packages in my env. So how can I debug in my kernel?

**Comment by JohanMabille** [comment]
Yes, for now only xeus-python supports debugging.
