### ISSUE TITLE
Filter _xpython variables

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#425]
Now that https://github.com/jupyter-xeus/xeus-python-wheel/pull/50 is merged, we should consider adding the following entries:

- `_xpython_get_connection_filename`
- `_xpython_launch`

to the variable filter list in:

https://github.com/jupyterlab/debugger/blob/e5cb406ff0e92c0a2f9aa5dff1f701583a74bb60/schema/main.json#L38-L48

This can be tested using the `xeus-python` wheel by installing `xeus-python` with: `pip install xeus-python`

**Comment by SylvainCorlay** [comment]
+1

In the longer term, could kernels advertize a list of variables to ignore in the debug info request? This could also include regex, such as `_xpython_*`

**Comment by jtpio** [comment]
> In the longer term, could kernels advertize a list of variables to ignore in the debug info request? This could also include regex, such as `_xpython_*`.

That sounds like it could be useful indeed.

For now since only one kernel supports debugging we can probably leave it in the settings as it is. But it would be great to look into this again in the future.
