### ISSUE TITLE
Breakpoints do not stop inside tf.data.Dataset map function

### ISSUE THREAD

**Issue by edurenye** [jupyterlab/debugger#435]
I was using tf.data.Dataset map and I get an error inside the map_func, so I tried to set a breakpoint to debug, but the breakpoint was ignored and the code executed fully.

I tried to see it it happens with the normal map function but it does not, it's just with tf.data.Dataset map, that I found until the moment, might happen with other functions.

I tried to replicate using the dummy function you will see below, and the execution did not stop at the breakpoint, so this is a issue. Not sure why this happens.

Here is a screenshot of the test I did:
![debug_map](https://user-images.githubusercontent.com/6824576/80998246-e3429a00-8e42-11ea-90ce-1a908eade62a.png)

**Comment by jtpio** [comment]
Thanks @edurenye for reporting this.

Do you have a minimal sample code that could be used to reproduce the issue?

**Comment by jtpio** [comment]
Thanks @edurenye!

I can confirm this is reproducible locally by creating a new conda environment with `tensorflow`:

```
conda create -n debugger-test -c conda-forge tensorflow python jupyterlab ptvsd xeus-python "notebook>6"
```

![tf-lab-map](https://user-images.githubusercontent.com/591645/81166884-9242bb00-8f94-11ea-8547-6d8bcf7566ef.gif)

Out of curiosity I tried to debug the same code snippet in VS Code:

![ts-vscode-map](https://user-images.githubusercontent.com/591645/81166660-27917f80-8f94-11ea-990f-a0e143c713bb.gif)

The breakpoint is also not hit when debugging in VS Code. Which means that the issue might be related to the underlying debugger in `ptvsd` / `debugpy`, used in both `@jupyterlab/debugger` and VS Code.

**Comment by SylvainCorlay** [comment]
Yes, I presume that the execution flow does a round trip through some native code in Pandas, and that the debugger looses track of it.

**Comment by jtpio** [comment]
> Which means that the issue might be related to the underlying debugger in `ptvsd` / `debugpy`, used in both `@jupyterlab/debugger` and VS Code.

Or to the way the `dataset.map` function is implemented in TensorFlow.

**Comment by edurenye** [comment]
So, where I should move the issue?

**Comment by jtpio** [comment]
> So, where I should move the issue?

Then probably [debugpy](https://github.com/microsoft/debugpy)? Although I haven't investigated more than trying the code snippet in VS Code (see screencast).

`debugpy` is the Python debugger [now used in VS Code](https://devblogs.microsoft.com/python/python-in-visual-studio-code-march-2020-release/) and the continuation of [ptvsd](https://github.com/microsoft/ptvsd) (currently used by `xeus-python`)

**Comment by edurenye** [comment]
The breakpoint does not work because the code is transformed to something else for the execution there, using 'eager execution' it can be debugged fine, so we can close this issue.

See https://github.com/tensorflow/tensorflow/issues/39320

Thank you very much everybody that helped and was involved in this issue!

But we should think about moving from [ptvsd](https://github.com/microsoft/ptvsd) to [debugpy](https://github.com/microsoft/debugpy).
I'll open a new issue for this.

**Comment by jtpio** [comment]
Thanks @edurenye for investigating this across the different repos!
