### ISSUE TITLE
Debugger slider button unresponsive in Jupyter Lab.

### ISSUE THREAD

**Issue by pratikchhapolika** [jupyterlab/debugger#437]
I am using jupyter lab and trying to embedd the debugger in it.

**Windows 10, 64 bit**, **Google Chrome**

Here are the steps I followed:

**conda create --name ml python=3.8.2
conda activate ml
conda install xeus-python=0.7.1 notebook=6 jupyterlab=2.1.2 -c conda-forge**

JupyterLab 2.0+
xeus-python 0.7.1+
notebook 6+

jupyter labextension install @jupyterlab/debugger
Then I start jupyter lab and it opens in Google Chrome:

Though I get the debugger button in xpython notebook but I am not able to turn it on. Here is the screenshot.

1. Tried restarting from anaconda navigator
2. Tried Running it with the default theme or on another browser

![jlab](https://user-images.githubusercontent.com/11159549/81168321-69cab900-8fb4-11ea-8381-0bfba53d321a.png)

**Comment by jtpio** [comment]
Thanks @pratikchhapolika.

Is `ptvsd` also installed? It looks like it is missing from:

> conda install xeus-python=0.7.1 notebook=6 jupyterlab=2.1.2 -c conda-forge

**Comment by SylvainCorlay** [comment]
ptvsd is not packaged for windows and Python 3.8 on conda-forge.

You could install it from pip.

**Comment by SylvainCorlay** [comment]
For all other versions of Python, and all other platform, ptvsd is a dependency of xeus-python.

**Comment by pratikchhapolika** [comment]
> Thanks @pratikchhapolika.
> 
> Is `ptvsd` also installed? It looks like it is missing from:
> 
> > conda install xeus-python=0.7.1 notebook=6 jupyterlab=2.1.2 -c conda-forge

I did install ptvsd as **pip install ptvsd**

**Comment by pratikchhapolika** [comment]
When trying to reinstall, got this error:

**Node v14.1.0

Yarn configuration loaded.
> "C:\Program Files\nodejs\npm.CMD" pack @jupyterlab/debugger
npm notice 
npm notice package: @jupyterlab/debugger@0.2.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE                             
npm notice 1.4kB  style/breakpoints.css               
npm notice 828B   style/callstack.css                 
npm notice 109B   style/console.css                   
npm notice 452B   style/editor.css                    
npm notice 1.2kB  style/icons.css                     
npm notice 824B   style/index.css                     
npm notice 1.4kB  style/sidebar.css                   
npm notice 447B   style/sources.css                   
npm notice 2.4kB  style/variables.css                 
npm notice 2.9kB  lib/breakpoints/body.js             
npm notice 1.8kB  lib/callstack/body.js               
npm notice 3.1kB  lib/sources/body.js                 
npm notice 2.1kB  lib/handlers/console.js             
npm notice 3.8kB  lib/debugger.js                     
npm notice 8.5kB  lib/handlers/editor.js              
npm notice 1.3kB  lib/sources/factory.js              
npm notice 973B   lib/handlers/file.js                
npm notice 9.6kB  lib/handler.js                      
npm notice 828B   lib/breakpoints/header.js           
npm notice 818B   lib/callstack/header.js             
npm notice 1.6kB  lib/sources/header.js               
npm notice 818B   lib/variables/header.js             
npm notice 1.2kB  lib/icons.js                        
npm notice 1.1kB  lib/breakpoints/index.js            
npm notice 1.6kB  lib/callstack/index.js              
npm notice 12.9kB lib/index.js                        
npm notice 1.3kB  lib/sources/index.js                
npm notice 2.7kB  lib/variables/index.js              
npm notice 2.0kB  lib/breakpoints/model.js            
npm notice 2.0kB  lib/callstack/model.js              
npm notice 2.5kB  lib/model.js                        
npm notice 1.4kB  lib/sources/model.js                
npm notice 1.1kB  lib/variables/model.js              
npm notice 2.4kB  lib/handlers/notebook.js            
npm notice 16.4kB lib/service.js                      
npm notice 5.0kB  lib/session.js                      
npm notice 4.7kB  lib/variables/table.js              
npm notice 287B   lib/tokens.js                       
npm notice 9.9kB  lib/handlers/tracker.js             
npm notice 4.1kB  lib/variables/tree.js               
npm notice 1.2kB  schema/main.json                    
npm notice 3.3kB  package.json                        
npm notice 2.1kB  README.md                           
npm notice 1.5kB  style/icons/activate-breakpoints.svg
npm notice 151B   style/icons/arrow-collapse.svg      
npm notice 131B   style/icons/arrow-expand.svg        
npm notice 766B   style/icons/class.svg               
npm notice 952B   style/icons/close-all.svg           
npm notice 348B   style/icons/enumerator.svg          
npm notice 525B   style/icons/step-into.svg           
npm notice 482B   style/icons/step-out.svg            
npm notice 609B   style/icons/step-over.svg           
npm notice 608B   style/icons/variable.svg            
npm notice 638B   style/icons/view-breakpoint.svg     
npm notice 503B   lib/breakpoints/body.d.ts           
npm notice 486B   lib/callstack/body.d.ts             
npm notice 1.4kB  lib/sources/body.d.ts               
npm notice 1.2kB  lib/handlers/console.d.ts           
npm notice 2.3kB  lib/debugger.d.ts                   
npm notice 2.8kB  lib/handlers/editor.d.ts            
npm notice 983B   lib/sources/factory.d.ts            
npm notice 1.1kB  lib/handlers/file.d.ts              
npm notice 3.0kB  lib/handler.d.ts                    
npm notice 376B   lib/breakpoints/header.d.ts         
npm notice 368B   lib/callstack/header.d.ts           
npm notice 465B   lib/sources/header.d.ts             
npm notice 368B   lib/variables/header.d.ts           
npm notice 418B   lib/icons.d.ts                      
npm notice 791B   lib/breakpoints/index.d.ts          
npm notice 1.4kB  lib/callstack/index.d.ts            
npm notice 610B   lib/index.d.ts                      
npm notice 951B   lib/sources/index.d.ts              
npm notice 1.5kB  lib/variables/index.d.ts            
npm notice 1.6kB  lib/breakpoints/model.d.ts          
npm notice 1.1kB  lib/callstack/model.d.ts            
npm notice 1.8kB  lib/model.d.ts                      
npm notice 1.7kB  lib/sources/model.d.ts              
npm notice 1.4kB  lib/variables/model.d.ts            
npm notice 1.5kB  lib/handlers/notebook.d.ts          
npm notice 6.1kB  lib/service.d.ts                    
npm notice 2.8kB  lib/session.d.ts                    
npm notice 2.5kB  lib/variables/table.d.ts            
npm notice 11.5kB lib/tokens.d.ts                     
npm notice 4.2kB  lib/handlers/tracker.d.ts           
npm notice 1.2kB  lib/variables/tree.d.ts             
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/debugger                    
npm notice version:       0.2.0                                   
npm notice filename:      jupyterlab-debugger-0.2.0.tgz           
npm notice package size:  38.1 kB                                 
npm notice unpacked size: 192.6 kB                                
npm notice shasum:        9940169f08558317d4659b474d162de6cbebf802
npm notice integrity:     sha512-AZGwBPkdVcT8V[...]mW7lahnM8qDJQ==
npm notice total files:   86                                      
npm notice 
jupyterlab-debugger-0.2.0.tgz

Node v14.1.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 114.69s.

> node C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
Done in 0.94s.

> node C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve './icons/filetype/python.svg' in 'C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\style'
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\webpack\lib\Compilation.js:925:10
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\neo-async\async.js:2830:7
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\neo-async\async.js:6877:13
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:184:12
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\Resolver.js:238:5
    at eval (eval at create (C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:22:13
    at C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:73:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
resolve './icons/filetype/python.svg' in 'C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\style'
  using description file: C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\package.json (relative path: ./style)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\package.json (relative path: ./style/icons/filetype/python.svg)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\style\icons\filetype\python.svg doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\style\icons\filetype\python.svg.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\style\icons\filetype\python.svg.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\style\icons\filetype\python.svg.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\style\icons\filetype\python.svg.json doesn't exist
      as directory
        C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\ui-components\style\icons\filetype\python.svg doesn't exist
child_process.js:632
    throw err;
    ^

Error: Command failed: C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\.bin\webpack.CMD --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12872,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\site-packages\jupyterlab\commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter**

**Comment by pratikchhapolika** [comment]
Any help on this? Also I noticed in the steps mentioned

**Installation
A kernel with support for debugging is required to be able to use the debugger.

It is generally recommended to create a new conda environment to install the dependencies:

conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.7.1 notebook=6 jupyterlab=2 ptvsd
conda activate jupyterlab-debugger
Then, run the following command to install the extension:

jupyter labextension install @jupyterlab/debugger**


We also need **nodejs** in windows 10.

**Comment by jtpio** [comment]
> We also need **nodejs** in windows 10.

Indeed, it is required to install new JupyterLab extensions. 

Would you like to open a PR to add it the `conda` command?

**Comment by pratikchhapolika** [comment]
> > We also need **nodejs** in windows 10.
> 
> Indeed, it is required to install new JupyterLab extensions.
> 
> Would you like to open a PR to add it the `conda` command?

What is PR? and how can i mention?

**Comment by jtpio** [comment]
> Exiting application: jupyter**

Is this a new issue after installing nodejs? In the first post it looks like JupyterLab starts fine.

**Comment by jtpio** [comment]
> What is PR? and how can i mention?

PR means "Pull Request", which is the term used to make contributions to open source repositories like this one. In this case that would mean forking the repo, editing README.md, and opening a PR using on GitHub.

**Comment by pratikchhapolika** [comment]
oh got it. Yes I can do that.

**Comment by pratikchhapolika** [comment]
> > Exiting application: jupyter**
> 
> Is this a new issue after installing nodejs? In the first post it looks like JupyterLab starts fine.

Yes. I am like tired of it. Sometime it works well and sometimes it doesn't. 
When I install .exe file of nodejs it installs **chocolatey** as well. Post that I get this error. There should be a concise step on how to install on windows 7/10.
