### ISSUE TITLE
Regarding concrete steps on installing it on Windows 10 using python and Anaconda

### ISSUE THREAD

**Issue by pratikchhapolika** [jupyterlab/debugger#439]
Hi Team,
**Its not an issue but a request that if anyone has installed debugger in Windows 10 and its working fine then please lists down the concrete steps that you have taken.**

One thing that I found hard with anaconda is it really messes up with environment variables. And then we have to uninstall and install that too after clearing the registry files.

Thanks,
Pratik

**Comment by asteppke** [comment]
The installation instructions almost worked for me on Windows 10. The step that is missing is the installation of nodejs.

So given a running miniconda installation create a new environment with the necessary components:

    conda create -n jupyterlab-debugger -c conda-forge xeus=0.23.14 xeus-python=0.7.1 notebook=6 jupyterlab=2 ptvsd

followed by
````
activate jupyterlab-debugger
conda install -c conda-forge nodejs
jupyter labextension install @jupyterlab/debugger
````

Then run jupyter lab, use a xeus kernel and it should work.

**Comment by jtpio** [comment]
Thanks @asteppke for chiming in!

We should add `nodejs` to the `conda create -n jupyterlab-debugger` command in the [README](https://github.com/jupyterlab/debugger/blob/master/README.md).

Would you like to open a pull request to add it? Thanks!

**Comment by asteppke** [comment]
@jtpio: Thanks for the great work on the debugger, I hope the community picks up the work on integration of their packages with xeus.

I tested this again in a new conda environment and it runs smoothly here. So I added the extra dependency to the conda command in the README and opened this pull request: https://github.com/jupyterlab/debugger/pull/461.

**Comment by jtpio** [comment]
@pratikchhapolika feel free to post here again if you have been able to give this another try.
