### ISSUE TITLE
Move from ptvsd to debugpy

### ISSUE THREAD

**Issue by edurenye** [jupyterlab/debugger#442]
We should think about moving from [ptvsd](https://github.com/microsoft/ptvsd) to [debugpy](https://github.com/microsoft/debugpy) as `ptvsd` has been deprecated and should replaced by `debugpy` that is the continuation of the same project under a different name.

Related:
https://github.com/jupyterlab/debugger/issues/435
https://github.com/jupyterlab/debugger/issues/398

**Comment by afshin** [comment]
This is on the roadmap for `xeus-python` and is a good idea. Cheers!

But it is not a JupyterLab debugger extension issue so let's close it here. I see that you've mentioned this in the kernel repository as well. Thank you!

**Comment by afshin** [comment]
cf. https://github.com/jupyter-xeus/xeus-python/issues/180#issuecomment-624905964
