### ISSUE TITLE
Is it possible to have a console to handle the variable while debugging?

### ISSUE THREAD

**Issue by Tapyu** [jupyterlab/debugger#449]
Hello, I'm new on Python and GitHub

Since I moved from Matlab to Python I have been struggling with the lack of a good debugging tool. On Matlab, It was possible to handle the variables saved in the workspace while I debugging the code, that is, I could call any Matlab command to modify the loaded variables without interrupt the debug.

Although /jupyterlab/debugger is a good tool, I don't find any similar "command window" (maybe pythonist call it console) to handle the data. Just see what's the data loaded in my system is not enough to get a good debug tool (in my humble opinion).

If anyone can gear me to the right way, I would be grateful.

**Comment by jtpio** [comment]
Thanks @Tapyu for the suggestion!

It's on the roadmap, and currently tracked in https://github.com/jupyterlab/debugger/issues/409 and https://github.com/jupyterlab/debugger/issues/419.

**Comment by Tapyu** [comment]
> Thanks @Tapyu for the suggestion!
> 
> It's on the roadmap, and currently tracked in #409 and #419.

I am glad to know that jtpio. Thank you.
