### ISSUE TITLE
Refactor the use of the editor finder

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#473]
Glancing at the code, it looks like the `EditorFinder` (used to find editors matching the temporary cells) is passed all the way down to the `EditorHandler` here:

https://github.com/jupyterlab/debugger/blob/a056c2853732fab577f2c4ec5c4b5a979bf862a1/src/handlers/editor.ts#L50

And used only once here:

https://github.com/jupyterlab/debugger/blob/a056c2853732fab577f2c4ec5c4b5a979bf862a1/src/handlers/editor.ts#L163-L168

This makes editor handlers very coupled to the `EditorFinder`.

Moreover the editor finder is passed to the `NotebookHandler` here:

https://github.com/jupyterlab/debugger/blob/a056c2853732fab577f2c4ec5c4b5a979bf862a1/src/handler.ts#L215-L219

But not to the `ConsoleHandler` and `FileHandler`:

https://github.com/jupyterlab/debugger/blob/a056c2853732fab577f2c4ec5c4b5a979bf862a1/src/handler.ts#L221-L232

Refactoring this should help fix #471 and #414, as a follow-up to https://github.com/jupyterlab/debugger/pull/454#pullrequestreview-429054162

**Comment by jtpio** [comment]
Another point to refactor is the use of the non-optional `focus` parameter as mentioned in https://github.com/jupyterlab/debugger/pull/454#discussion_r437469928:

https://github.com/jupyterlab/debugger/blob/a056c2853732fab577f2c4ec5c4b5a979bf862a1/src/editor-finder.ts#L77-L81

**Comment by KrzysztofSikoraCodete** [comment]
Good point. We definitely pass the editor-finder object too deeply.

**Comment by jtpio** [comment]
Fixed by #474.
