### ISSUE TITLE
Debugger enabled, but not populating

### ISSUE THREAD

**Issue by aguthrie19** [jupyterlab/debugger#479]
The debugger extension appears but does not provide any additional functionality: the cell's breakpoint sidebar doesn't appear, neither do the debugger cells populate after running cells.

![image](https://user-images.githubusercontent.com/1246274/86112617-125d3c80-ba7d-11ea-9641-80a3bd73c88f.png)

I'm running JupyterLab in this docker image:
https://hub.docker.com/r/jupyter/minimal-notebook 
and have additionally configured my container by
```
RUN pip install xeus-python
RUN jupyter labextension install @jupyterlab/debugger
```

**Comment by aguthrie19** [comment]
On a similar note of trying to debug variables, I notice that the property inspector window pops out and is unviewable in a docker container. Should I open a ticket for this? How would I pop-in the property inspector window since I'm running on a docker container and I don't want to forward the desktop?

**Comment by jtpio** [comment]
Thanks @aguthrie19 for the detailed issue.

The `xeus-python` package on pip has not been updated to the latest `0.8.0` version yet (0.8.0 is required by the latest `@jupyterlab/debugger`)

From there I can see 2 options:

- Install `xeus-python=0.8` from conda in the Dockerfile
- Use the previous `@jupyterlab/debugger@0.2.0`

**Comment by aguthrie19** [comment]
Thank you for the quick response Jeremy @jtpio.
I've added `RUN jupyter labextension install @jupyterlab/debugger@0.2.0` to my Dockerfile and indeed appear to be running this version of debugger, yet still no interactivity.

```
~$ jupyter labextension list
JupyterLab v2.1.3
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyterlab/debugger v0.2.0  enabled  OK
```
![image](https://user-images.githubusercontent.com/1246274/86213654-e69a8f00-bb2e-11ea-99b1-5440e7bf1bcb.png)

**Comment by aguthrie19** [comment]
Resolved by updating the xpython kernel `conda install xeus-python=0.8.0 `

![image](https://user-images.githubusercontent.com/1246274/86215433-6de90200-bb31-11ea-8aae-348da2b63eb5.png)

**Comment by jtpio** [comment]
Thanks @aguthrie19 for testing. Closing as fixed!

**Comment by sknigh** [comment]
xeus-python 0.8.3 is now in pypi and I am able to install 3.0.0 betas with pip.
