### ISSUE TITLE
Fontawesome 4 css

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/debugger#480]
Having this css that is very specific to fontawesome 4 is messing things up in jlab 2, where we've upgraded to fontawesome 5:

https://github.com/jupyterlab/debugger/blob/38d724014319aa54cd287d1d231632e188a89849/style/index.css#L15-L21

It overrides the global `.fa` class so that the fontawesome 5 shim does not properly work, and I think it breaks fontawesome for everyone else that is using the `.fa` class in jlab 2.

**Comment by jtpio** [comment]
Thanks @jasongrout for catching this.

Looking at the git it seems like this is a leftover from the very early iterations that didn't get cleaned up.

Just opened #481 to remove it.
