### ISSUE TITLE
Matplotlib not working using xeus-python kernel

### ISSUE THREAD

**Issue by Atcold** [jupyterlab/debugger#482]
If choosing xeus-python as a kernel, matplotlib stops working.

And if I `%matplotlib inline` then I get:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
In  [6]:
Line 1:     %matplotlib inline

ValueError: magics not found
---------------------------------------------------------------------------
```

**Comment by jtpio** [comment]
Thanks @Atcold.

Would it be possible to move the issue to the `xeus-python` repository? https://github.com/jupyter-xeus/xeus-python

**Comment by Atcold** [comment]
@jtpio, are you asking *me* to close it and reopen it there, or…?

**Comment by arush1947** [comment]
hi @jtpio
Not sure if this thread has been moved elsewhere but I am facing the exact same issue. It would be greatly appreciated if you could resolve this issue :)

%matplotlib inline
-----------------------------------------------------
Line 35:    return compile(source, filename, mode, PyCF_ONLY_AST)
SyntaxError: invalid syntax (<string>, line 1)
-----------------------------------------------------

**Comment by jtpio** [comment]
@Atcold yes it would be better to close this issue and open a new one on the xeus-python repo (since it doesn't seem related to the debugger extension)

**Comment by Atcold** [comment]
Here is the issue https://github.com/jupyter-xeus/xeus-python/issues/224#issue-589099455

**Comment by jtpio** [comment]
Thanks!
