### ISSUE TITLE
can not see the slider of debugger

### ISSUE THREAD

**Issue by niklew515** [jupyterlab/debugger#487]
I have installed the debugger in jupyterlab extension, but I can't see the slider as the official document shows. What should I do ? 
![微信图片_20200710031712](https://user-images.githubusercontent.com/44541315/87076566-e8fe9680-c25c-11ea-9c37-c517b8c0bdf0.png)

here is  what the official document look like:
![222](https://user-images.githubusercontent.com/44541315/87076638-fa47a300-c25c-11ea-9106-9f665da698a2.png)

**Comment by jtpio** [comment]
hey @niklew515,

It looks like the notebook on the first screenshot is using the default Python kernel.

For now the debugger is only available for the `xeus-python` kernel, which would have to be installed as mentioned in https://github.com/jupyterlab/debugger#usage.

**Comment by dipanjank** [comment]
I also have the same problem - can't see the debugger enable / disable slider in the notebook when I'm using the xpython kernel. Is there any information I can give you to help debug the issue?

On ubuntu 18.04

$ python --version
Python 3.6.10 :: Anaconda, Inc.

$ pip freeze 
certifi==2020.6.20
importlib-metadata==1.7.0
jedi==0.17.1
jupyter-lsp==0.8.0
parso==0.7.0
pluggy==0.13.1
ptvsd==4.3.2
Pygments==2.6.1
python-jsonrpc-server==0.3.4
python-language-server==0.34.1
ujson==1.35
xeus-python==0.7.1
zipp==3.1.0

jupyterlab is 2.1.5 installed using conda.

**Comment by jtpio** [comment]
@dipanjank if you've installed `@jupyterlab/debugger` version `0.3.0-beta.3`, then you'll need `xeus-python=0.8`.

To get the version of the lab extension:

```
jupyter labextension list
```

If possible, we usually recommend creating a new conda environment and using `conda` to install `xeus-python`:

```
conda install -c conda-forge xeus-python
```

(more info in https://github.com/jupyterlab/debugger#installation)

**Comment by dipanjank** [comment]
Thanks! Do you know when xeus-python 0.8 will be available in pip? I'm surprised that it's in conda but not in pip.

**Comment by jtpio** [comment]
@dipanjank yes it's available on PyPI as well (for Linux): https://pypi.org/project/xeus-python

Closing as answered, since the latest version on PyPI should now support the latest `@jupyterlab/debugger` release. 

Feel free to post here or open a new issue if you have more questions!
