### ISSUE TITLE
dumpCell request

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/debugger#49]
Although most of the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/specification) can be directly used, there is a usecase specific to Jupyterlab that requires an additional message type.

When setting breakpoints, the debugger expects a source path which must refer to a file on disk. Since the cells of a notebook are executed by the interpreter, it not possible to directly set breakpoints in them. The solution is to first require the backend to dump the cell in a file, and then use this file as the source path argument of the `setBreakpoints` request. This can be achieved with the following additional messages:

Message type: `debug_request`
```python
content = {
  'type': 'request',
  # Sequence number (also known as message ID).
  # For protocol messages of type 'request' this ID can be used to cancel the request.
  'seq': 'number',
  'command': 'dumpCell',
  'arguments': {
    # Source code of the cell, one or more lines
    'code': str
  }
}
```

When receiving this request, the backend "computes" a filename, write the content of the cell in it, and returns the name of the file:

Message_type `debug_reply`
```python
content = {
  'type': 'response',
  # Sequence number of the corresponding request.
  'request_seq': 'number',
  # Outcome of the request
  'success': 'bool',
  'command': 'dumpCell',
  'body': {
    # Name of the file where the cell was dumped
    # Can be used as the 'sourcePath' argument in a 'setBreakpoints' request
    'sourcePath': 'str'
  }
}
```

**Comment by jtpio** [comment]
Thanks @JohanMabille for the details :+1: 

This will simplify quite a few things on the frontend side (managing current and next `cell_id`)

**Comment by jtpio** [comment]
The new `dumpCell` message was added in https://github.com/jupyterlab/debugger/pull/50, replacing `updateCell`.

Thanks @JohanMabille!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/should-jupyter-recommend-a-text-based-representation-of-the-notebook/3273/3
