### ISSUE TITLE
Prepare public interfaces for merging into JupyterLab core

### ISSUE THREAD

**Issue by afshin** [jupyterlab/debugger#493]
- [ ] **MAYBE** `ISession` should not expose any of its start/stop/etc. functionality and instead the `IDebugger` interface should pass those methods through. We should discuss this further.
- [x] `IEditorFinder#find` should return an array instead of an iterator

**Comment by jtpio** [comment]
Also related and maybe worth considering: https://github.com/jupyterlab/debugger/issues/450

**Comment by jtpio** [comment]
Looking into https://github.com/jupyterlab/debugger/issues/495, it looks like we could also removed `focus` from `IEditorFinder.Params`, so the editor finder doesn't have any side-effect on the widgets, and is only responsible for finding the code editors.

This would require the caller of `IEditorFinder#find` to implement the focus logic, for example:

https://github.com/jupyterlab/debugger/blob/4f56bb73da45e758416bd7a2c743f901cebfef72/src/editor-finder.ts#L94-L100

But we would need a way to find the notebook, console or file editor widget from a `CodeEditor.IEditor`.

**Comment by jtpio** [comment]
It should now also be possible to remove the `tracker` plugin:

https://github.com/jupyterlab/debugger/blob/9698d6f252ce4a366b7300a57e32cfbe0326b92a/src/index.ts#L233-L234

And move the remaining of the logic: 

https://github.com/jupyterlab/debugger/blob/9698d6f252ce4a366b7300a57e32cfbe0326b92a/src/handlers/tracker.ts#L45-L63

To the `main` plugin:

https://github.com/jupyterlab/debugger/blob/9698d6f252ce4a366b7300a57e32cfbe0326b92a/src/index.ts#L390

See discussions in https://github.com/jupyterlab/debugger/pull/501 for more context.

**Comment by jtpio** [comment]
- [ ] Also, this alias could be either removed or moved to the token definitions:

https://github.com/jupyterlab/debugger/blob/9698d6f252ce4a366b7300a57e32cfbe0326b92a/src/panels/callstack/model.ts#L79

**Comment by jtpio** [comment]
> Also, this alias could be either removed or moved to the token definitions:

It could probably be moved to `tokens.ts`, similar to `IDebugger.IBreakpoint`:

https://github.com/jupyterlab/debugger/blob/20efafc9eac4ded21a14d5a6e668f205e1fe056e/src/tokens.ts#L176

And named `IStackFrame`.

Or as a type alias:

```typescript
export type StackFrame = DebugProtocol.StackFrame
```

**Comment by jtpio** [comment]
> MAYBE ISession should not expose any of its start/stop/etc. functionality and instead the IDebugger interface should pass those methods through. We should discuss this further.

Should we address this one as well? It looks like the remaining item on the list.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/debugger/pull/509 https://github.com/jupyterlab/debugger/pull/507 https://github.com/jupyterlab/debugger/pull/501 https://github.com/jupyterlab/debugger/pull/494 https://github.com/jupyterlab/debugger/pull/522
