### ISSUE TITLE
Debugger does not highlight current line as a ribbon on main code area

### ISSUE THREAD

**Issue by yimmas** [jupyterlab/debugger#525]
I set up a breakpoint on the editable main code area. ( I can see the breakpoint on the main code area & on the  right breakpoints section). When i  run the code it stops at the breakpoint successfully. But it does not highlight( orange ribbon ) the breakpoint line on the main editable code section. It does highlight on the lower right "Source"  section. I can move the next line of the code via pressing next. It does update on the source section but nothing happens  like highlighting the next line of the code on the main area.

On your animated gif , i can see that it is being highlighted as a ribbon on the main area. Does it have any setting to enable it?

I am happy to provide any logs if needed.

thanks.

**Comment by afshin** [comment]
Thanks for the bug report! Could you please tell us the version of JupyterLab `jupyter lab --version`? Also if possible could you show a screenshot as well? Thank you!

**Comment by yimmas** [comment]
Hi,

(py3) PS D:\DMP\condabin> jupyter lab --version
2.2.2

![jlab_debugger](https://user-images.githubusercontent.com/63968961/89049151-7d8a7f00-d359-11ea-8f2d-9e00f8d4fc51.gif)

**Comment by afshin** [comment]
Thank you!

**Comment by yimmas** [comment]
Your welcome & thanks for creating this awesome debugger. 
If any logs needed i can provide .
 I  did disable all the extensions except this and it still does not show on the main area.

**Comment by jtpio** [comment]
@yimmas would it be possible to try with the JupyterLab 3.0.0rc1 pre-release? (which now ships with the debugger extension)

It can be installed using the following command (preferably in a new environment):

```
python -m pip install --pre jupyterlab
```

**Comment by jtpio** [comment]
It might be similar to https://github.com/jupyterlab/debugger/issues/418 (also running on Windows)

**Comment by jtpio** [comment]
@yimmas would it be possible to try with the latest `xeus-python` (0.8.6), which should include a fix for windows users (handling of `\` in paths that was causing the line to not be highlighted)

**Comment by jtpio** [comment]
Closing as answered.

@yimmas feel free to open a new issue in https://github.com/jupyterlab/jupyterlab if you are still experiencing problems with the latest releases of JupyterLab and xeus-python. Thanks!
