### ISSUE TITLE
Add default configuration override to show extension by default

### ISSUE THREAD

**Issue by mnowacki-b** [jupyterlab/debugger#526]
Currently if there is not kernel spec available, that have metadata with 'debugger' flag set, the extension will be disabled (see https://github.com/jupyterlab/debugger/blob/master/src/index.ts#L387 ). 

It would be nice to have an override where we could enable/disable the extension by default even if the specs are not available.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/debugger/pull/527
