### ISSUE TITLE
Debugger breakpoint setting does not work after kernel restart

### ISSUE THREAD

**Issue by yimmas** [jupyterlab/debugger#530]
for a new file , i am able to start with a xpython kernel and acitvate debugger. I am also successful setting a breakpoint ( orange dot for selection , red dot for setting it).

** But when i restart the kernel , activate the debugger again  I am not able to  mark as red dot  by double clicking for  setting the breakpoint.

** Also  after trying to set a failed breakpoint , the debugger deactivate button does not work.

![jlab_debugger2_bug](https://user-images.githubusercontent.com/63968961/90608685-a50f9180-e20b-11ea-8f39-2049da3f282e.gif)

**Comment by yimmas** [comment]
Looks like a envirement & dloaded extensions/module issue. Did a fresh env with necessary extension & dependincies and the issue is gone.

**Comment by afshin** [comment]
Sorry for the late response but glad for the resolution! :joy:
