### ISSUE TITLE
Extension Installation Error

### ISSUE THREAD

**Issue by fritol** [jupyterlab/debugger#534]
I am running jupyterlab2.1.5 jupyter nb 6.0.3and still getting this:

Extension Installation Error
An error occurred installing @jupyterlab/debugger-extension.

Error message:

No version of @jupyterlab/debugger-extension could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.2 <2.2.0          >=3.0.0-beta.0 <4.0.0@jupyterlab/application
>=2.1.1 <2.2.0          >=3.0.0-beta.0 <4.0.0@jupyterlab/apputils
>=2.1.2 <2.2.0          >=3.0.0-beta.0 <4.0.0@jupyterlab/console
>=4.1.0 <4.2.0          >=5.0.0-beta.0 <6.0.0@jupyterlab/coreutils
>=2.1.2 <2.2.0          >=3.0.0-beta.0 <4.0.0@jupyterlab/fileeditor
>=2.1.2 <2.2.0          >=3.0.0-beta.0 <4.0.0@jupyterlab/notebook
>=5.1.0 <5.2.0          >=6.0.0-beta.0 <7.0.0@jupyterlab/services

**Comment by afshin** [comment]
I see this behavior too. I think we must have a bug in the versions in the dependencies. We should fix this for 0.3.x and JupyterLab 2.x.

Please note that as of JupyterLab 3.0 (which is in beta right now and will be released in about a month) the debugger ships as a core extension.

**Comment by jtpio** [comment]
This is most likely related to the changes from https://github.com/jupyterlab/debugger/pull/462 and https://github.com/jupyterlab/debugger/pull/497 when `@jupyterlab/testutils` was bumped to `2.2.0`.

**Comment by Benjamin-Siebold** [comment]
Is there any resolve on this other than using jupyterlab 3.0?

**Comment by jtpio** [comment]
> An error occurred installing @jupyterlab/debugger-extension.

For JupyterLab 2.x, the proper way to install the extension with `@jupyterlab/debugger`.

`@jupyterlab/debugger-extension` is for JupyterLab 3.0, and doesn't have to be installed manually anymore since it ships with 3.0 by default.

**Comment by jtpio** [comment]
Closing as answered.

@Benjamin-Siebold @fritol let us know if you have any other issue!
