### ISSUE TITLE
can we debug nodejs/js code using visual debugger ?

### ISSUE THREAD

**Issue by actcod01** [jupyterlab/debugger#537]
When I use [PixieDust](https://github.com/pixiedust/pixiedust), I able to execute nodejs code in jupyterlab , but unable to debug it as xpython visual debugger

**Comment by jtpio** [comment]
Thanks @actcod01.

This is indeed not supported by `xeus-python`, but it would be really nice to have JavaScript / node kernel that supports debugging!

**Comment by jtpio** [comment]
Closing as answered and also since this is not directly specific to the debugger extension.
