### ISSUE TITLE
kernel dies: no module named xpython_launcher

### ISSUE THREAD

**Issue by gioxc88** [jupyterlab/debugger#547]
I created a virtual environment in a folder called `c:\dev\projects\base\venv\`
and installed jupyter lab and xeus python and the debugger extension in this venv.
After activating the venv and running the lab I can see that the lab is correctly being loaded from the venv folder:

`JupyterLab extension loaded from c:\dev\projects\base\venv\lib\site-packages\jupyterlab`

But when I start jupyter lab and try to select xpython kernel, the kernel dies soon after it started and in the jupyter server log I can see :

`C:\Users\***\AppData\Local\Programs\Python\Python38\python.exe: No module named xpython_launcher`

so it is looking for xpython in the system installation folder instead of the venv folder which is `c:\dev\projects\base\venv\`

 any idea on how to solve this?
Thank you

**Comment by jtpio** [comment]
Thanks @gioxc88. 

Which version of `xeus-python` is it?

Also if the error happens when creating a new notebook, it is most likely more related to the `xeus-python` kernel itself.

Would it be possible to open the issue on https://github.com/jupyter-xeus/xeus-python?

**Comment by jtpio** [comment]
Closing since this sounds more like an issue with `xeus-python`.
