### ISSUE TITLE
Installation error: Couldn't find package "murmurhash-js@^1.0.0" and "vscode-debugprotocol@^1.37.0"

### ISSUE THREAD

**Issue by bwojang** [jupyterlab/debugger#548]
I'm new to jupyter and when I follow the [installation](https://github.com/jupyterlab/debugger#installation) part of this debugger, an error occurred. I was installing it on ubuntu 20.04. I followed the exact installing command in the above link without changing and it went well. However, after 
 `jupyter labextension install @jupyterlab/debugger`, the error occurred.
```
(base) myname@mylaptop:~$ conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.8.0 notebook=6 jupyterlab=2 ptvsd nodejs
(base) myname@mylaptop:~$ conda activate jupyterlab-debugger 
(jupyterlab-debugger) myname@mylaptop:~$ jupyter labextension install @jupyterlab/debugger
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-hft3ilxo.log
```

and this is the error info in the log:
```
Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /home/myname/miniconda3/envs/jupyterlab-debugger/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Couldn't find package "murmurhash-js@^1.0.0" required by "@jupyterlab/debugger@file:../extensions/jupyterlab-debugger-0.3.3.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "vscode-debugprotocol@^1.37.0" required by "@jupyterlab/debugger@file:../extensions/jupyterlab-debugger-0.3.3.tgz" on the "npm" registry.
    at /home/myname/miniconda3/envs/jupyterlab-debugger/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/home/myname/miniconda3/envs/jupyterlab-debugger/share/jupyter/lab/staging/yarn.js:310:30)
    at /home/myname/miniconda3/envs/jupyterlab-debugger/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

npm dependencies failed to install
Traceback (most recent call last):

  File "/home/myname/miniconda3/envs/jupyterlab-debugger/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/myname/miniconda3/envs/jupyterlab-debugger/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,

  File "/home/myname/miniconda3/envs/jupyterlab-debugger/lib/python3.8/site-packages/jupyterlab/commands.py", line 459, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/home/myname/miniconda3/envs/jupyterlab-debugger/lib/python3.8/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install
```

I've tried 3 different network environments and the error kept unchanged. So it seems not a network issue. 
Any ideas would be appreciated.

**Comment by bwojang** [comment]
btw, there is [an open question](https://stackoverflow.com/questions/61895524/install-a-visual-debugger-for-jupyter) raised months ago on stackoverflow that is almost identical.

**Comment by jtpio** [comment]
hi @bwojang,

The logs say that this might be because of the network connection.

Were you able to retry installing it?

**Comment by bwojang** [comment]
> hi @bwojang,
> 
> The logs say that this might be because of the network connection.
> 
> Were you able to retry installing it?

hi @jtpio ,
Thanks for the reply. As I mentioned in my post, it doesn't seem like a network connection problem. I've reinstalled it quite a few times, with different versions and under different networks. I got exactly the same results.

**Comment by jtpio** [comment]
Ah ok, thanks for getting back.

Weird because both `vscode-debugprotocol` and `murmurhash-js` are still available on npm of course.

Just in case: are you using a private npm registry / mirror? (this could sometimes explain why packages are not found if not cached or mirrored correctly).

As an alternative, you could try installing the latest `jupyterlab` release candidate with:

`pip install jupyterlab --pre`

or:

`conda install -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc jupyterlab=3`

JupyterLab 3.0 ships with the debugger extension by default.

However 3.0 might not suit your needs just yet as some third-party extensions still need to update their compatibility range. But it should be fine if you just want to test the debugger extension.

**Comment by bwojang** [comment]
> Ah ok, thanks for getting back.
> 
> Weird because both `vscode-debugprotocol` and `murmurhash-js` are still available on npm of course.
> 
> Just in case: are you using a private npm registry / mirror? (this could sometimes explain why packages are not found if not cached or mirrored correctly).
> 
> As an alternative, you could try installing the latest `jupyterlab` release candidate with:
> 
> `pip install jupyterlab --pre`
> 
> or:
> 
> `conda install -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc jupyterlab=3`
> 
> JupyterLab 3.0 ships with the debugger extension by default.
> 
> However 3.0 might not suit your needs just yet as some third-party extensions still need to update their compatibility range. But it should be fine if you just want to test the debugger extension.

Thanks, @jtpio .
For the first question, today I did create some `.npmrc` and  `.yarnrc` files to redirect the registry, as recommended in a few forums I searched, in order to attempt to solve this problem, and all efforts failed. The records I posted here are with the clearest environment as I could keep, all those configs had been cleansed. The result is identical to the one I got at the very beginning. Indeed I can't make sure that there's absolutely no extra private config is set, but I don't know how to check it. 
***
For the latest `jupyterlab` release, I really prefer this solution. I tried the `conda` command you mentioned, and the whole process is as following:
```
(base) myname@mylaptop:~$ conda create -n jupyterlab3-basic 
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/myname/miniconda3/envs/jupyterlab3-basic



Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate jupyterlab3-basic
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) myname@mylaptop:~$ conda activate jupyterlab3-basic 
(jupyterlab3-basic) myname@mylaptop:~$ conda install -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc jupyterlab=3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

ResolvePackageNotFound: 
  - jupyter_server[version='>=1.0.1,<2.0.0']

```
 Do you have any suggestions? Thanks.

**Comment by jtpio** [comment]
@bwojang for the second option, you might have to specify the `conda-forge` channel too (and add xeus-python too to install it in one go):

```
conda install -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc -c conda-forge jupyterlab=3 xeus-python
```

**Comment by bwojang** [comment]
> @bwojang for the second option, you might have to specify the `conda-forge` channel too (and add xeus-python too to install it in one go):
> 
> ```
> conda install -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc -c conda-forge jupyterlab=3 xeus-python
> ```

Oh that really works! Thank you so much @jtpio !

**Comment by jtpio** [comment]
@bwojang should we close the issue, if using JupyterLab 3 is fine for you?

**Comment by bwojang** [comment]
The workaround is [using JupyterLab 3](https://github.com/jupyterlab/debugger/issues/548#issuecomment-704151985).
