### ISSUE TITLE
Keep shown variables structure while continuing execution?

### ISSUE THREAD

**Issue by deeplook** [jupyterlab/debugger#557]
I'm using  @jupyterlab/debugger v0.3.3 (love it!) and find that when clicking to "Continue" executing the next statement it would be quite nice for the "Variables" section to keep their state of shown nested structures (being collapsed or expanded) as they are. Otherwise it's a bit of a click fest. ;)

**Comment by jtpio** [comment]
Thanks @deeplook!

Yes it's something that has been discussed and it would feel natural to have the state of the variables always in the sidebar.

And is now tracked in: https://github.com/jupyterlab/jupyterlab/issues/9114

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/9114 to keep the discussion in one place.
