### ISSUE TITLE
Out of memory error when jupyter lab build after install the debugger extention destruct the whole page.

### ISSUE THREAD

**Issue by psi-cmd** [jupyterlab/debugger#558]
I don't know if it's better to ask in jupyter repo or here, but I have to try to fix the problem.

I install the extention from the jupyter lab page, and it requires rebuild. And the VM crashed due to out of memory ( in WSL2 in windows). And when I try to restart the jupyter lab and visit the webpage, page fail to render and raise red logs as below:

![image](https://user-images.githubusercontent.com/47203885/96701476-3a253700-13c3-11eb-9109-574fdbcc197c.png)

> [W 17:21:00.272 LabApp] 500 GET /lab/api/settings/?1603272060211 (127.0.0.1): Failed parsing schema (@jupyterlab/debugger:main): Expecting value: line 1 column 1 (char 0)                      
[W 17:21:00.273 LabApp] Failed parsing schema (@jupyterlab/debugger:main): Expecting value: line 1 column 1 (char 0)                                                                            
[E 17:21:00.273 LabApp] {                                                                                                                                                                             
"Host": "localhost:8888",                                                                                                                                                                       
"Connection": "keep-alive",                                                                                                                                                                     
"X-Xsrftoken": "2|54ca8b66|ffe53b287d2ebcd42f74937a2245eb6c|1603241399",                                                                                                                        
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",                                                             
"Content-Type": "application/json",                                                                                                                                                             
"Accept": "*/*",                                                                                                                                                                                
"Sec-Fetch-Site": "same-origin",                                                                                                                                                                
"Sec-Fetch-Mode": "cors",                                                                                                                                                                       
"Sec-Fetch-Dest": "empty",                                                                                                                                                                      
"Referer": "http://localhost:8888/lab?",                                                                                                                                                        
"Accept-Encoding": "gzip, deflate, br",                                                                                                                                                         
"Accept-Language": "en,zh-CN;q=0.9,zh;q=0.8,zh-TW;q=0.7,en-US;q=0.6",                                                                                                                           
"Cookie": "_xsrf=2|54ca8b66|ffe53b287d2ebcd42f74937a2245eb6c|1603241399; username-localhost-8888=\"2|1:0|10:1603270405|23:username-localhost-8888|44:NGE4ZGE2MDY3Y2IzNDNlMjhlNmU3YmM2ODM1YzYzMmY=|71279371e988dea3002007f9cbfcd0fec2871c77c7d2879421599710f1692af4\""                                                                                                                         }                                                                                                                                                                                           
[E 17:21:00.273 LabApp] 500 GET /lab/api/settings/?1603272060211 (127.0.0.1) 11.34ms referer=http://localhost:8888/lab?                                                                         
[W 17:21:02.113 LabApp] Build recommended                                                                                                                                                       
[W 17:21:02.113 LabApp] jupyterlab_filetree needs to be included in build                                                                                                                       
[W 17:21:02.113 LabApp] jupyterlab-theme-solarized-dark needs to be included in build                                                                                                           
[W 17:21:02.113 LabApp] @jupyter-voila/jupyterlab-preview needs to be included in build                                                                                                         
[W 17:21:02.113 LabApp] jupyterlab-drawio needs to be included in build                                                                                                                         
[W 17:21:02.113 LabApp] @telamonian/theme-darcula needs to be included in build                                                                                                                 
[W 17:21:02.113 LabApp] jupyterlab-recents needs to be included in build                                                                                                                        
^C[I 17:21:05.312 LabApp] interrupted

Then I try to uninstall the extention with `jupyter-labextension uninstall @jupyterlab/debugger`. It tells me success.

However when I try to rebuild the jupyter lab with `jupyter lab build --dev-build=False --minimize=False`(option was suggested by `jupyter lab --help` when last failure due to out of memory), and launch jupyter lab again, it just repeat the problem as the picture above, which means I can't get rid of the extention by uninstall.

If there is any other issue to be the reference, or anyone can help with this issue? Thanks very much.

**Comment by psi-cmd** [comment]
Oh, I finally locate the `Failed parsing schema` in jupyterlab_server module, set_trace with pdb, and caught the json loading error and the json path.

The problem is that when building after install the extension, main.json under `jupyter/lab/schemas/@jupyterlab/debugger` was created as an empty file temporarily, and then memory run out. Leaving a json load failure to next startup of jupyter lab.

(But the drawback is: the extension sidebar can't display anything, just blank)

**Comment by jtpio** [comment]
Thanks @psi-cmd.

Since the debugger extension is now shipped in JupyterLab 3.0 by default, were you able to try with JupyterLab 3.0 final?

Which can be installed with `pip install jupyterlab` or updated with `pip install -U jupyterlab`.

> [W 17:21:02.113 LabApp] Build recommended
> [W 17:21:02.113 LabApp] jupyterlab_filetree needs to be included in build
> [W 17:21:02.113 LabApp] jupyterlab-theme-solarized-dark needs to be included in build
> [W 17:21:02.113 LabApp] @jupyter-voila/jupyterlab-preview needs to be included in build
> [W 17:21:02.113 LabApp] jupyterlab-drawio needs to be included in build
> [W 17:21:02.113 LabApp] @telamonian/theme-darcula needs to be included in build
> [W 17:21:02.113 LabApp] jupyterlab-recents needs to be included in build

Also as a side note it looks like some of these extensions still need to be published so they are compatible with 3.0, which might take up to a couple of weeks.

**Comment by psi-cmd** [comment]
Oh, I finally realize that behaviour is not unique to debugger extension after running into another memory run-out. And the solution is just `jupyter labextention uninstall <full name of plugin that cause error>`, then `jupyter lab rebuild`. Then you may reinstall the plugin if you like.

**Comment by jtpio** [comment]
OK, thanks @psi-cmd for getting back and posting the details.

Let's close the issue then if it's not related to the debugger extension. And feel free to open new issues in https://github.com/jupyterlab/jupyterlab if you would like to. Thanks!
