### ISSUE TITLE
Ability to move debugger to left side bar

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/debugger#560]
Hello there, is there a way to move the debugger to the left bar, and hide the right side bar if empty ?
It feels like I'm loosing a whole column of workspace only for one extension

**Comment by jtpio** [comment]
@mocquin this should be possible by right clicking on the icon and choosing "Switch Sidebar Side":

![switch-sidebar](https://user-images.githubusercontent.com/591645/98600431-d5803c80-22dd-11eb-9a63-271c4df24364.gif)

This actually applies to other items too.

**Comment by mocquin** [comment]
Thanks, I went looking in the settings but did not try right click. Now I know !
