### ISSUE TITLE
Modify variable value within debugging console.

### ISSUE THREAD

**Issue by Leonolovich** [jupyterlab/debugger#561]
VS Code allowed me to set up a breakpoint and then interact with the console one the breakpoint was reached. I was the able to change the value of a variable and continue execution after the breakpoint with the variable having the new value. This is helpful when using a lot of conditional statements that you can change at will during execution.

I have not seen, or at least figured out, how to do this using the debugger. I thought the 'New Console for Notebook' option would allow me to interact with it, but the cell in the new console window will only execute after the cell being debugged is done executing.

Is there a way to get this to work?

**Comment by jtpio** [comment]
Thanks @Leonolovich.

It's not implemented yet, but is currently tracked in this issue: https://github.com/jupyterlab/jupyterlab/issues/9111

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/9111 to keep the discussion in one place.
