### ISSUE TITLE
Difference between xeus python, python 3 and python 3.8

### ISSUE THREAD

**Issue by ppseverin** [jupyterlab/debugger#568]
My question is about Kernels and Python version. I would really like to use debugger extenion, but it says I need to switch kernel (currently Python 3) to xeus python.

My question is, does this means that I will work with other version of Python? Or his has nothing to do with Python's verion? I'm currently using Python 3.8.

Sorry the noob question :(

**Comment by SylvainCorlay** [comment]
Hello, this is a fine question, and it shows that we are not clear about the message.

There are two implementation of Jupyter kernels for Python
 -  ipykernel (which shows "Python X.X" in the upper right corner of the notebook)

and 

 - xeus-python (which shows "Python X.X (XPython)" in the upper right corner of the notebook.

The latter is a reimplementation of Python kernel which supports the debug protocol, and can be installed with conda/mamba (if you use conda) or pip.

**Comment by ppseverin** [comment]
So, if I understood this well, using ipykernel (which is Python 3) or using Xeus-Python has nothing to do with the version of Python I'm using? (which is 3.8, at the time of writing). Is this correct?

**Comment by JohanMabille** [comment]
Yes, both ipykernel and xeus-python can be used with different versions of Python, these notions (which kernel, and which version of Python) are independent.

**Comment by jtpio** [comment]
Closing as answered, thanks all!
