### ISSUE TITLE
RuntimeError: JupyterLab failed to build

### ISSUE THREAD

**Issue by gitgithan** [jupyterlab/debugger#573]
I have activated a virtualenv in windows and pip install jupyterlab (3.0.5) and windows installer installed nodejs from official site and ran `jupyter labextension install @jupyterlab/debugger` to get the error in title.

From the log, common lines i see are 
```
webpack 5.14.0 compiled with [1m[31m1 error[39m[22m in 522 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
`webpack 5.14.0 compiled with [1m[31m1 error[39m[22m in 305 ms`
`TypeError: The 'compilation' argument must be an instance of Compilation`

Anyone know what's going on and how can I install this extension? 
It looks like a problem with other libraries?

**Comment by jtpio** [comment]
Thanks @gitgithan.

>  pip install jupyterlab (3.0.5)

If you have JupyterLab 3.0, then the debugger is installed automatically.

You would only need to install a kernel with support for debugging, such as `xeus-python`, with the following command:

```bash
conda install -c conda-forge xeus-python
```

Or 

```bash
pip install xeus-python
```

And then reload the page.

**Comment by gitgithan** [comment]
Thanks that worked and I did not need to run `jupyter labextension install @jupyterlab/debugger`.
