### ISSUE TITLE
Interactive charts using pandas dataframe plot function

### ISSUE THREAD

**Issue by jnarula5** [jupyterlab/debugger#578]
Hi,

I want to use pandas dataframe plot function to display interactive charts in jupyter notebook using xpython kernel.

Can you please guide how to do that?

Thanks,
JN

**Comment by jtpio** [comment]
@jnarula5 closing this issue as this doesn't seem to be related to the debugger.

A way forward would be to open an issue in https://github.com/jupyter-xeus/xeus-python.

Or come chat on gitter: https://gitter.im/QuantStack/Lobby
