### ISSUE TITLE
how to install debugger on an existing env?

### ISSUE THREAD

**Issue by seyeeet** [jupyterlab/debugger#580]
the instruction on the webstite works find
```
conda create -n jupyterlab-debugger -c conda-forge xeus-python=0.9 jupyterlab=3
conda activate jupyterlab-debugger
```
my question is how I can install the debugger on an existing env.
I have an env that is set and I dont want to create a new one just for debugging.
Is there a way to install and work with the debugger on an existing env?

**Comment by JohanMabille** [comment]
Yes, once you've activated your environment, you can run

```bash
conda install jupyterlab-debugger  xeus-python -c conda-frge
```

However, the debugger has been integrated into Jupyter Lab 3, so installing xeus-python should be enough if you already have Jupyter Lab 3 installed.

**Comment by seyeeet** [comment]
@JohanMabille got it thanks, do I need to also do `jupyter labextension install @jupyterlab/debugger` after installation of aforementioned packages?

**Comment by JohanMabille** [comment]
If you use Jupyter Lab 2 and the debugger extension, yes. If you use Jupyter Lab 3, everything should be already available.
