### ISSUE TITLE
Right way to add jupyterlab-debugger on Jupyterhub

### ISSUE THREAD

**Issue by snassimr** [jupyterlab/debugger#581]
If this integration possible in case of default conda environment and kernels for users

**Comment by SylvainCorlay** [comment]
The JupyterLab debugger is not part of jupyterlab 3.0 stable, and this extension is not required anymore. We will soon archive the repository.

**Comment by snassimr** [comment]
Hi ,
Sorry , but I don't really understand your answer . Should I post the question on some another forum ? My question was about Jupyterhub

**Comment by SylvainCorlay** [comment]
The reason why I closed the issue, is that as soon as you are using jupyterlab>=3.0, the debugger frontend is already included (whether with JupyterHub or not).

**Comment by SylvainCorlay** [comment]
In order to be able to use the debugger, you need a Jupyter kernel that supports debugging.

For the Python programming language, the only such kernel for now is xeus-python (ipykernel will soon spport debugging as well).

**Comment by snassimr** [comment]
Yep . That the question I searched the answer for. I am using ipykernel . Thanks . How can I follow up for this feature to get the notification once it's available
