### ISSUE TITLE
Use debug events to control the state of the session

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#59]
Quoting https://github.com/jupyterlab/debugger/pull/53#issue-327671083:

> the '_isStarted' cache variable in the DebuggerSession object should be updated upon event notification

We can make use of the [debug events](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized) instead to set `_isStarted`

**Comment by JohanMabille** [comment]
I have just read the protocol again, it seems that for attach and disconnect we can simply wait for the replies.

**Comment by jtpio** [comment]
That would make things simpler :+1:
