### ISSUE TITLE
Resize Name and Value columns in the Variables table

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#74]
Ideally we should be able to resize the "Name" and "Value" columns in the "Variables" table, to be able to read long variable names:

![image](https://user-images.githubusercontent.com/591645/67194377-4add4e80-f3f7-11e9-8829-034b69887338.png)

**Comment by jtpio** [comment]
Not something to tackle now, but to keep in mind for later.

We might actually consider using a tree instead of a table (mentioned in https://github.com/jupyterlab/debugger/issues/30). Using a tree would also make it easier to display classes (https://github.com/jupyterlab/debugger/issues/23).

**Comment by KsavinN** [comment]
Done in #66
