### ISSUE TITLE
Restore the debugger session's state

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/debugger#88]
If a user switches back to a notebook whose code execution was interrupted on a breakpoint, or if she reloads the page while the code execution is interrupted on a breakpoint, what should the behavior be? Should we be able to restore the full state, that is highlight the line where the code stopped, and restore the breakpoints and callstack? Or should we simply restart the debugger (and resume the code execution)?

I think the first behavior (restoring everything) would be a butter user experience, however this requires additional changes in the backend.

**Comment by jtpio** [comment]
What happens when the execution is stopped and then we stop the debugger? (sending the `disconnect` message)

From the previous tests I think the `request_execute` goes through, so on page reload the kernel will have executed the cell (except that the debugger will be stopped).

**Comment by JohanMabille** [comment]
The decision taken during developers meetings is to fully restore the state of a debugger session when the user switches back to it (either because the user switches back to a notebook with a running debugger or upon page reload).

This implies that the backend must store the list of breakpoints and a list of threads that are stopped.
This data can be retrieved with a debugInfo request.

The forntend must be able to map the temporary filenames created in the backend for setting the breakpoints with the cells of the notebooks where the breakpoints should appear.

The current method for creating a file in the backend) is to hash the content of the cell (this gives the name of the file) and then add a prefix and the ".py" suffix. Therefore, even if the frontend can work with the hash only, it must be available to retrieve this hash in a filename when receiving a debugInfo reply.

The easiest way to do it is that the backend also sends the prefix and the suffix that are used to build the filenames. The frontend does not need to store them, they are used when ahndling the debugInfo reply only.

**Comment by JohanMabille** [comment]
This has been implemented in #153 and #165
