### ISSUE TITLE
Architecture of the debugger

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/debugger#90]
Nothing blocking at all, these are just some questions and thoughts about how internal components should interact.

- Should we hide the DebugSession behind the DebugService? In this case, the DebugService would provide methods to set the session, start and stop it.
- Should the DebugService only provide methods to send debug request and react to debug events? In this case, it would be responsible for updating the "data" of different model classes (Breakpoints, Variables).
- Should the debugger model hold other model classes (breakpoints, variables)?

cc @afshin @jtpio @KsavinN

**Comment by jtpio** [comment]
> Should we hide the DebugSession behind the DebugService? In this case, the DebugService would provide methods to set the session, start and stop it.

> Should the DebugService only provide methods to send debug request and react to debug events? In this case, it would be responsible for updating the "data" of different model classes (Breakpoints, Variables).

We might not need the service actually. The model would expose higher level method such as `setBreakpoints` or `getVariables`, and would update its state on response.

Still using its `DebugSession` for sending messages to the kernel.

>  Should the debugger model hold other model classes (breakpoints, variables)?

With `model` being a `DebuggerModel`, `model.breakpoints` a `Breakpoints.Model` and so on.

UI elements could update their states on `model.breakpointsChanged` and other signals.

**Comment by JohanMabille** [comment]
> We might not need the service actually. The model would expose higher level method such as setBreakpoints or getVariables, and would update its state on response

Actually I would like to keep the model as simple as possible, basically data (or other data models as you described) and signals, and implement the logic in a dedicated class.

**Comment by JohanMabille** [comment]
So basically we have the following options:

1] The service has a reference on the model which only contains data / other data models and signals that emit when the data change. The service is connected to these signals so he can send the appropriate requests to the kernel. The model does not know the service.

2] The model owns the service and connects its slots to the signals of the service (which will basically only forward debug events). When data is changed, the model calls the appropriate service method.

3] The service is directly implemented in the model. It is equivalent to 2] but simpler (although more monolithic). In that case we definitely need to expose an IModel interface if we want to be able to drive the debugger from other plugins / parts of the app.

#93 implements (partially) the first option, which is better regarding the principle of separation of concerns. The drawbacks is that it slightly complicates the workflow, however, if we keep dedicated models for breakpoints and callstacks, we will have to connect slots to their data changed signal anyway (at least to notify the main model).

**Comment by JohanMabille** [comment]
Here is a overview of the target architecture:

![debugger_arch](https://user-images.githubusercontent.com/6754742/67498269-74a8a680-f67f-11e9-9536-75e711be4f8b.png)

**Comment by jtpio** [comment]
Closing as now implemented.

Thanks @JohanMabille!
