### ISSUE TITLE
Display classes in variables

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#95]
For now classes (and potentially other nested data types) don't have their attributes displayed:

![image](https://user-images.githubusercontent.com/591645/67489130-4fad3700-f671-11e9-9c53-549787ac9430.png)

We'll probably need a few extra calls to `variables` and send the right `variablesReference`. 

As a reference in VS Code:

![image](https://user-images.githubusercontent.com/591645/67489217-7e2b1200-f671-11e9-8284-720fe97dd3c8.png)

**Comment by KsavinN** [comment]
Is this issue related to bad sending request or with backend?

**Comment by JohanMabille** [comment]
The backend is really stupid regarding these requests, it forwards the request to the debugger and sends back the reply to the frontend (it is mainly an adapter between DAP protocol and Jupyter protocol ), so I think additional requests should be sent (or the request should be filled with additional parameters).

A mean to get the right parameters if to test with VSCode and ptvsd logs enabled. This way we can inspect all the debug requests received and the reponses and events emitted by PTVSD.

**Comment by jtpio** [comment]
Looking at the logs in VS Code, additional `variables` requests are sent when expanding the `a` object (screenshot above). But they are not sent initially, only on demand.

**Comment by jtpio** [comment]
We can add that to https://github.com/jupyterlab/debugger/issues/64

**Comment by martinRenou** [comment]
Maybe it would make sense to do this extra request lazily? i.e. only do it if the user clicks on the variable they want to see

**Comment by jtpio** [comment]
> Maybe it would make sense to do this extra request lazily? i.e. only do it if the user clicks on the variable they want to see

Yes this is what is happening in VS Code.

**Comment by jtpio** [comment]
For reference:

![vscode-debug-logs](https://user-images.githubusercontent.com/591645/67572027-a54b1780-f735-11e9-90f1-1237e4399ae2.gif)

I will add that to #64

**Comment by KsavinN** [comment]
was resolve with #125
