### ISSUE TITLE
Restore open sidebar

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/debugger#96]
At the moment if we open the sidebar and then reload the page, the sidebar will be minimized:

![restore-sidebar-state](https://user-images.githubusercontent.com/591645/67507982-58613580-f690-11e9-9304-eda879dff1b7.gif)

It would be great if the sidebar could keep its "open" state on reload.

**Comment by KsavinN** [comment]
It seems issue related to the tab bar. Do you know how to get access to instance of tabs?

**Comment by jtpio** [comment]
> It seems issue related to the tab bar. Do you know how to get access to instance of tabs?

What does `tab bar` refer to here?

**Comment by jtpio** [comment]
It looks like the sidebar is never saved to the workspace file. For example when inspecting the workspace file with:

`$ cat ${CONDA_PREFIX}/etc/jupyter/lab/workspaces/lab-a511.jupyterlab-workspace | jq '.'`

```json
{
  "data": {
    "layout-restorer:data": {
      "main": {
        "dock": {
          "type": "tab-area",
          "currentIndex": 0,
          "widgets": []
        },
        "mode": "multiple-document"
      },
      "left": {
        "collapsed": false,
        "current": "command-palette",
        "widgets": [
          "filebrowser",
          "running-sessions",
          "command-palette",
          "tab-manager"
        ]
      },
      "right": {
        "collapsed": false,
        "widgets": []
      }
    },
    "debugger:0d08301c-902b-4f59-ad55-eab74f97e7c2": {
      "data": {
        "id": "0d08301c-902b-4f59-ad55-eab74f97e7c2"
      }
    },
    "mode": "condensed"
  },
  "metadata": {
    "id": "/lab"
  }
}
```
